-- ============================================================================
-- QUARANTINE the orphan table public."L"  (reversible — see orphan-L-restore.sql)
--
-- Owner decision 5 (2026-10-03, ledger R293): the table is ORPHAN/UNKNOWN; do
-- not drop it; audit it completely; if it is proven unused and not part of
-- Lambda NX, remove it only through a documented, reversible migration.
--
-- ## Audit evidence (read-only, live project roykbyzkskhmzclzobmd, 2026-10-03)
--
--   * Not in the Lambda NX schema: absent from db/schema.ts, db/schema.sql and
--     all 24 migrations. No source file in app/, lib/, db/, scripts/ or
--     netlify/ references it, and the app uses no Supabase client or Realtime.
--   * Shape is the Supabase dashboard "new table" template: `id bigint`
--     GENERATED BY DEFAULT AS IDENTITY primary key, `created_at timestamptz
--     default now()`. No comment, no other column.
--   * Never written: 0 rows; its identity sequence "L_id_seq" has
--     is_called = false (no insert has ever drawn a value); n_tup_ins/upd/del
--     = 0. One sequential scan (consistent with a dashboard view).
--   * Nothing depends on it: no foreign keys in or out, no views, no
--     triggers, no policies, no function bodies naming it.
--   * It is the ONLY table in the `supabase_realtime` publication — the
--     dashboard's "Enable Realtime" checkbox — and realtime.subscription holds
--     0 subscriptions, none on it.
--   * Logs (24 h window available): 0 mentions across postgrest, postgres,
--     pgbouncer, supavisor, realtime, edge, auth and storage logs.
--   * Created after `group_members` and before `blobs` (pg_class oid order
--     18164 < 18414 < 18514), i.e. by hand while the schema was being applied.
--
-- ## Why quarantine instead of DROP
--
-- Moving the table to a non-exposed schema removes it from `public` (and so
-- from PostgREST, Realtime and every advisor that scans `public`) while losing
-- nothing: rows (none), sequence state, constraint, ownership and grants all
-- survive and the restore script puts it back exactly. A DROP is a separate,
-- later decision for the owner, once the quarantine has stood without anyone
-- missing the table.
--
-- ## Safety
--
-- One transaction. It refuses to run if the table has gained rows or no
-- longer exists in `public`, so it can never move data somebody started
-- using after this audit. Idempotent in effect: a second run finds nothing in
-- `public` and stops with a notice.
-- ============================================================================

BEGIN;

DO $$
BEGIN
  IF to_regclass('public."L"') IS NULL THEN
    RAISE NOTICE 'public."L" not present — nothing to quarantine';
    RETURN;
  END IF;

  IF (SELECT count(*) FROM public."L") <> 0 THEN
    RAISE EXCEPTION 'public."L" now holds rows — audit is stale, refusing to move it';
  END IF;

  EXECUTE 'CREATE SCHEMA IF NOT EXISTS lambda_orphaned';
  EXECUTE $c$COMMENT ON SCHEMA lambda_orphaned IS
    'Quarantine for objects found in the Lambda NX database that are not part of Lambda NX. Not exposed through the API. See db/ops/orphan-L-quarantine.sql.'$c$;
  EXECUTE 'REVOKE ALL ON SCHEMA lambda_orphaned FROM PUBLIC';
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    EXECUTE 'REVOKE ALL ON SCHEMA lambda_orphaned FROM anon';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    EXECUTE 'REVOKE ALL ON SCHEMA lambda_orphaned FROM authenticated';
  END IF;

  IF EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'L'
  ) THEN
    EXECUTE 'ALTER PUBLICATION supabase_realtime DROP TABLE public."L"';
  END IF;

  -- The identity sequence is owned by the column and moves with the table.
  EXECUTE 'ALTER TABLE public."L" SET SCHEMA lambda_orphaned';

  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
    EXECUTE 'REVOKE ALL ON lambda_orphaned."L" FROM service_role';
  END IF;

  EXECUTE $c$COMMENT ON TABLE lambda_orphaned."L" IS
    'ORPHAN/UNKNOWN — quarantined 2026-10-03 (ledger R293). Not part of Lambda NX; never written. Restore: db/ops/orphan-L-restore.sql.'$c$;
END $$;

COMMIT;

-- Verify:
--   SELECT to_regclass('public."L"') AS in_public,            -- expect NULL
--          to_regclass('lambda_orphaned."L"') AS quarantined, -- expect lambda_orphaned."L"
--          (SELECT count(*) FROM pg_publication_tables WHERE tablename = 'L') AS in_publication; -- expect 0
