/**
 * Generated by scripts/build-stamp.mjs. Do not edit by hand.
 *
 * A constant rather than an environment variable read at runtime: the compiler
 * inlines it into the server and the browser bundle alike, so both report the
 * same build instead of two readings of a clock. See the script for the
 * hydration bug that made this necessary.
 */

/** When this build was produced, ISO-8601. */
export const BUILT_AT = "2026-08-22T04:39:59.193Z"

/** The commit it was produced from, or an empty string if nothing said. */
export const BUILT_FROM = "d1b7923525b6e23ad1a39610f487ce0c1d5ff7be"
