/**
 * Generated by scripts/build-stamp.mjs. Do not edit by hand.
 *
 * A constant rather than an environment variable read at runtime: the compiler
 * inlines it into the server and the browser bundle alike, so both report the
 * same build instead of two readings of a clock. See the script for the
 * hydration bug that made this necessary.
 */

/** When this build was produced, ISO-8601. */
export const BUILT_AT = "2026-08-27T02:17:23.902Z"

/** The commit it was produced from, or an empty string if nothing said. */
export const BUILT_FROM = "33434477f0407c17df9bb124240393ea9a1ef364"
