/**
 * The whole schema as one string — GENERATED, do not edit.
 *
 * Written by scripts/build-schema.mjs alongside db/schema.sql, from the
 * migrations in db/migrations. Edit a migration and regenerate; editing this
 * file by hand makes it disagree with the migrations, and db/schema-sql.test.ts
 * will fail rather than let that reach a database.
 *
 * It exists as TypeScript so the serverless bundler can see it. See the note
 * in scripts/build-schema.mjs.
 */

export const SCHEMA_SQL = `-- Lambda NX — the whole schema, in one paste.
--
-- Generated by scripts/build-schema.mjs from db/migrations. Do not edit by
-- hand: edit a migration and regenerate, or the two will disagree about what
-- the schema is.
--
-- Safe to run more than once. Every statement is guarded, so a partial
-- earlier run does not have to be unpicked before this one.
-- Covers 22 migrations, 0000_init.sql … 0021_email_followers.sql.

-- ─────────────────────────────────────────────────────────────
-- 0000_init.sql

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$CREATE TYPE "public"."auth_provider" AS ENUM('pi', 'standalone')$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$CREATE TYPE "public"."confidence" AS ENUM('confirmed', 'probable', 'possible', 'unconfirmed')$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$CREATE TYPE "public"."entity_type" AS ENUM('domain', 'ip', 'email', 'username', 'organization', 'phone', 'url', 'image', 'wallet', 'other')$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$CREATE TYPE "public"."investigation_status" AS ENUM('open', 'archived')$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$CREATE TYPE "public"."monitor_status" AS ENUM('active', 'paused')$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$CREATE TYPE "public"."radar_kind" AS ENUM('internal', 'product')$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$CREATE TYPE "public"."scan_status" AS ENUM('queued', 'running', 'done', 'error')$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

CREATE TABLE IF NOT EXISTS "alerts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"monitor_id" uuid NOT NULL,
	"title" text NOT NULL,
	"detail" jsonb,
	"seen" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "entities" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"investigation_id" uuid NOT NULL,
	"type" "entity_type" NOT NULL,
	"value" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "entities_investigation_type_value_uq" UNIQUE("investigation_id","type","value")
);

CREATE TABLE IF NOT EXISTS "entity_links" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"investigation_id" uuid NOT NULL,
	"from_entity_id" uuid NOT NULL,
	"to_entity_id" uuid NOT NULL,
	"relation" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "evidence" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"investigation_id" uuid NOT NULL,
	"entity_id" uuid,
	"claim" text NOT NULL,
	"source_key" text,
	"source_url" text,
	"retrieved_at" timestamp with time zone DEFAULT now() NOT NULL,
	"archive_url" text,
	"content_hash" text,
	"admiralty_source" char(1),
	"admiralty_info" integer,
	"confidence" "confidence" DEFAULT 'possible' NOT NULL,
	"notes" text,
	"raw" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "investigations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"title" text NOT NULL,
	"target_type" "entity_type" NOT NULL,
	"target_value" text NOT NULL,
	"status" "investigation_status" DEFAULT 'open' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "monitors" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"target_type" "entity_type" NOT NULL,
	"target_value" text NOT NULL,
	"interval_minutes" integer DEFAULT 1440 NOT NULL,
	"status" "monitor_status" DEFAULT 'active' NOT NULL,
	"last_run_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "radar_findings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"kind" "radar_kind" NOT NULL,
	"title" text NOT NULL,
	"summary" text,
	"source_url" text,
	"retrieved_at" timestamp with time zone DEFAULT now() NOT NULL,
	"confidence" "confidence" DEFAULT 'possible' NOT NULL,
	"dedupe_hash" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "radar_findings_dedupe_hash_unique" UNIQUE("dedupe_hash")
);

CREATE TABLE IF NOT EXISTS "scans" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"investigation_id" uuid,
	"source_key" text NOT NULL,
	"input" text NOT NULL,
	"status" "scan_status" DEFAULT 'queued' NOT NULL,
	"started_at" timestamp with time zone,
	"finished_at" timestamp with time zone,
	"error" text,
	"result" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "sources" (
	"key" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"capability" text NOT NULL,
	"passive" boolean DEFAULT true NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL
);

CREATE TABLE IF NOT EXISTS "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"auth_provider" "auth_provider" NOT NULL,
	"external_id" text NOT NULL,
	"display_name" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_provider_external_uq" UNIQUE("auth_provider","external_id")
);

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$ALTER TABLE "alerts" ADD CONSTRAINT "alerts_monitor_id_monitors_id_fk" FOREIGN KEY ("monitor_id") REFERENCES "public"."monitors"("id") ON DELETE cascade ON UPDATE no action$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$ALTER TABLE "entities" ADD CONSTRAINT "entities_investigation_id_investigations_id_fk" FOREIGN KEY ("investigation_id") REFERENCES "public"."investigations"("id") ON DELETE cascade ON UPDATE no action$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$ALTER TABLE "entity_links" ADD CONSTRAINT "entity_links_investigation_id_investigations_id_fk" FOREIGN KEY ("investigation_id") REFERENCES "public"."investigations"("id") ON DELETE cascade ON UPDATE no action$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$ALTER TABLE "entity_links" ADD CONSTRAINT "entity_links_from_entity_id_entities_id_fk" FOREIGN KEY ("from_entity_id") REFERENCES "public"."entities"("id") ON DELETE cascade ON UPDATE no action$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$ALTER TABLE "entity_links" ADD CONSTRAINT "entity_links_to_entity_id_entities_id_fk" FOREIGN KEY ("to_entity_id") REFERENCES "public"."entities"("id") ON DELETE cascade ON UPDATE no action$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$ALTER TABLE "evidence" ADD CONSTRAINT "evidence_investigation_id_investigations_id_fk" FOREIGN KEY ("investigation_id") REFERENCES "public"."investigations"("id") ON DELETE cascade ON UPDATE no action$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$ALTER TABLE "evidence" ADD CONSTRAINT "evidence_entity_id_entities_id_fk" FOREIGN KEY ("entity_id") REFERENCES "public"."entities"("id") ON DELETE set null ON UPDATE no action$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$ALTER TABLE "evidence" ADD CONSTRAINT "evidence_source_key_sources_key_fk" FOREIGN KEY ("source_key") REFERENCES "public"."sources"("key") ON DELETE no action ON UPDATE no action$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$ALTER TABLE "investigations" ADD CONSTRAINT "investigations_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$ALTER TABLE "monitors" ADD CONSTRAINT "monitors_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$ALTER TABLE "scans" ADD CONSTRAINT "scans_investigation_id_investigations_id_fk" FOREIGN KEY ("investigation_id") REFERENCES "public"."investigations"("id") ON DELETE cascade ON UPDATE no action$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$ALTER TABLE "scans" ADD CONSTRAINT "scans_source_key_sources_key_fk" FOREIGN KEY ("source_key") REFERENCES "public"."sources"("key") ON DELETE no action ON UPDATE no action$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

CREATE INDEX IF NOT EXISTS "alerts_monitor_idx" ON "alerts" USING btree ("monitor_id");

CREATE INDEX IF NOT EXISTS "entities_investigation_idx" ON "entities" USING btree ("investigation_id");

CREATE INDEX IF NOT EXISTS "entity_links_investigation_idx" ON "entity_links" USING btree ("investigation_id");

CREATE INDEX IF NOT EXISTS "evidence_investigation_idx" ON "evidence" USING btree ("investigation_id");

CREATE INDEX IF NOT EXISTS "monitors_user_idx" ON "monitors" USING btree ("user_id");

CREATE INDEX IF NOT EXISTS "scans_investigation_idx" ON "scans" USING btree ("investigation_id");

-- ─────────────────────────────────────────────────────────────
-- 0001_radar_fingerprint.sql

ALTER TABLE "monitors" ADD COLUMN IF NOT EXISTS "last_fingerprint" text;

-- ─────────────────────────────────────────────────────────────
-- 0002_credentials.sql

CREATE TABLE IF NOT EXISTS "credentials" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"email" text NOT NULL,
	"password_hash" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "credentials_user_id_unique" UNIQUE("user_id"),
	CONSTRAINT "credentials_email_unique" UNIQUE("email")
);

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$ALTER TABLE "credentials" ADD CONSTRAINT "credentials_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

-- ─────────────────────────────────────────────────────────────
-- 0003_entity_types.sql

ALTER TYPE "public"."entity_type" ADD VALUE IF NOT EXISTS 'company' BEFORE 'other';

ALTER TYPE "public"."entity_type" ADD VALUE IF NOT EXISTS 'person' BEFORE 'other';

-- ─────────────────────────────────────────────────────────────
-- 0004_complex_doctor_faustus.sql

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$CREATE TYPE "public"."effort" AS ENUM('small', 'medium', 'large')$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$CREATE TYPE "public"."impact" AS ENUM('low', 'medium', 'high', 'critical')$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$CREATE TYPE "public"."suggestion_kind" AS ENUM('feature', 'improvement', 'bug', 'integration', 'data_source', 'other')$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$CREATE TYPE "public"."suggestion_status" AS ENUM('new', 'triaged', 'planned', 'in_progress', 'shipped', 'declined')$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

CREATE TABLE IF NOT EXISTS "suggestions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid,
	"title" text NOT NULL,
	"body" text NOT NULL,
	"locale" text,
	"kind" "suggestion_kind" DEFAULT 'other' NOT NULL,
	"status" "suggestion_status" DEFAULT 'new' NOT NULL,
	"category" text,
	"impact" "impact",
	"effort" "effort",
	"sentiment" text,
	"summary" text,
	"tags" jsonb,
	"cluster_key" text,
	"submitter_weight" integer DEFAULT 1 NOT NULL,
	"votes" integer DEFAULT 0 NOT NULL,
	"triaged_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$ALTER TABLE "suggestions" ADD CONSTRAINT "suggestions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

CREATE INDEX IF NOT EXISTS "suggestions_status_idx" ON "suggestions" USING btree ("status");

CREATE INDEX IF NOT EXISTS "suggestions_cluster_idx" ON "suggestions" USING btree ("cluster_key");

CREATE INDEX IF NOT EXISTS "suggestions_user_idx" ON "suggestions" USING btree ("user_id");

-- ─────────────────────────────────────────────────────────────
-- 0005_majestic_zarek.sql

CREATE TABLE IF NOT EXISTS "ontology_edges" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"from_node_id" uuid NOT NULL,
	"to_node_id" uuid NOT NULL,
	"predicate" text NOT NULL,
	"confidence" "confidence" DEFAULT 'possible' NOT NULL,
	"sources" jsonb,
	"evidence_count" integer DEFAULT 1 NOT NULL,
	"first_seen" timestamp with time zone DEFAULT now() NOT NULL,
	"last_seen" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ontology_edges_uq" UNIQUE("from_node_id","to_node_id","predicate")
);

CREATE TABLE IF NOT EXISTS "ontology_nodes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"type" "entity_type" NOT NULL,
	"value" text NOT NULL,
	"mentions" integer DEFAULT 1 NOT NULL,
	"sources" jsonb,
	"first_seen" timestamp with time zone DEFAULT now() NOT NULL,
	"last_seen" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ontology_nodes_type_value_uq" UNIQUE("type","value")
);

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$ALTER TABLE "ontology_edges" ADD CONSTRAINT "ontology_edges_from_node_id_ontology_nodes_id_fk" FOREIGN KEY ("from_node_id") REFERENCES "public"."ontology_nodes"("id") ON DELETE cascade ON UPDATE no action$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$ALTER TABLE "ontology_edges" ADD CONSTRAINT "ontology_edges_to_node_id_ontology_nodes_id_fk" FOREIGN KEY ("to_node_id") REFERENCES "public"."ontology_nodes"("id") ON DELETE cascade ON UPDATE no action$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

CREATE INDEX IF NOT EXISTS "ontology_edges_from_idx" ON "ontology_edges" USING btree ("from_node_id");

CREATE INDEX IF NOT EXISTS "ontology_edges_to_idx" ON "ontology_edges" USING btree ("to_node_id");

-- ─────────────────────────────────────────────────────────────
-- 0006_public_jasper_sitwell.sql

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$CREATE TYPE "public"."calibration_author_kind" AS ENUM('us', 'external')$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$CREATE TYPE "public"."calibration_outcome" AS ENUM('correct', 'partial', 'wrong')$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$CREATE TYPE "public"."calibration_status" AS ENUM('open', 'resolved')$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

CREATE TABLE IF NOT EXISTS "calibration_claims" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"author_kind" "calibration_author_kind" NOT NULL,
	"author" text NOT NULL,
	"claim" text NOT NULL,
	"topic" text,
	"asserted_at" timestamp with time zone DEFAULT now() NOT NULL,
	"horizon" timestamp with time zone,
	"status" "calibration_status" DEFAULT 'open' NOT NULL,
	"outcome" "calibration_outcome",
	"resolved_at" timestamp with time zone,
	"note" text,
	"source_url" text,
	"confidence" "confidence" DEFAULT 'possible' NOT NULL,
	"dedupe_hash" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "calibration_claims_dedupe_hash_unique" UNIQUE("dedupe_hash")
);

CREATE INDEX IF NOT EXISTS "calibration_status_idx" ON "calibration_claims" USING btree ("status");

CREATE INDEX IF NOT EXISTS "calibration_horizon_idx" ON "calibration_claims" USING btree ("horizon");

CREATE INDEX IF NOT EXISTS "calibration_author_idx" ON "calibration_claims" USING btree ("author");

-- ─────────────────────────────────────────────────────────────
-- 0007_colossal_quasimodo.sql

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$CREATE TYPE "public"."plan" AS ENUM('free', 'pro')$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "plan" "plan" DEFAULT 'free' NOT NULL;

-- ─────────────────────────────────────────────────────────────
-- 0008_complex_proemial_gods.sql

ALTER TABLE "radar_findings" ADD COLUMN IF NOT EXISTS "admiralty" text;

ALTER TABLE "radar_findings" ADD COLUMN IF NOT EXISTS "feed" text;

-- ─────────────────────────────────────────────────────────────
-- 0009_plain_union_jack.sql

CREATE TABLE IF NOT EXISTS "visitors" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"subject_key" text NOT NULL,
	"user_id" uuid,
	"provider" "auth_provider",
	"display_name" text,
	"country_code" char(2),
	"country_name" text,
	"region" text,
	"last_mode" text,
	"visit_count" integer DEFAULT 1 NOT NULL,
	"first_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "visitors_subject_uq" UNIQUE("subject_key")
);

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$ALTER TABLE "visitors" ADD CONSTRAINT "visitors_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

CREATE INDEX IF NOT EXISTS "visitors_country_idx" ON "visitors" USING btree ("country_code");

CREATE INDEX IF NOT EXISTS "visitors_last_seen_idx" ON "visitors" USING btree ("last_seen_at");

-- Lockdown posture: RLS on, no policies. Only the service role (the app, via
-- DATABASE_URL) can touch this table; anon/authenticated are denied. This
-- registry is admin-only and is never reached from the client.
ALTER TABLE "visitors" ENABLE ROW LEVEL SECURITY;

-- ─────────────────────────────────────────────────────────────
-- 0010_tough_wonder_man.sql

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$CREATE TYPE "public"."post_kind" AS ENUM('post', 'research', 'signal')$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$CREATE TYPE "public"."post_visibility" AS ENUM('public', 'unlisted')$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

CREATE TABLE IF NOT EXISTS "posts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"author_user_id" uuid,
	"author_name" text,
	"kind" "post_kind" DEFAULT 'post' NOT NULL,
	"title" text NOT NULL,
	"body" text NOT NULL,
	"source_url" text,
	"ref_type" text,
	"ref_value" text,
	"locale" text,
	"visibility" "post_visibility" DEFAULT 'public' NOT NULL,
	"like_count" integer DEFAULT 0 NOT NULL,
	"repost_count" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$ALTER TABLE "posts" ADD CONSTRAINT "posts_author_user_id_users_id_fk" FOREIGN KEY ("author_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

CREATE INDEX IF NOT EXISTS "posts_visibility_created_idx" ON "posts" USING btree ("visibility","created_at");

CREATE INDEX IF NOT EXISTS "posts_author_idx" ON "posts" USING btree ("author_user_id");

-- Lockdown posture (matches every other table): RLS on, no policies. Only the
-- app's service connection reads/writes; all publishing goes through our API,
-- which enforces authorship and public/unlisted visibility server-side.
ALTER TABLE "posts" ENABLE ROW LEVEL SECURITY;

-- ─────────────────────────────────────────────────────────────
-- 0011_tan_terror.sql

ALTER TABLE "credentials" ALTER COLUMN "email" DROP NOT NULL;

ALTER TABLE "credentials" ADD COLUMN IF NOT EXISTS "pi_username" text;

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$ALTER TABLE "credentials" ADD CONSTRAINT "credentials_pi_username_unique" UNIQUE("pi_username")$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

-- ─────────────────────────────────────────────────────────────
-- 0012_broken_firebrand.sql

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$CREATE TYPE "public"."social_platform" AS ENUM('webhook', 'discord', 'slack', 'telegram')$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

CREATE TABLE IF NOT EXISTS "social_channels" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"platform" "social_platform" NOT NULL,
	"label" text NOT NULL,
	"target" text NOT NULL,
	"secret_enc" text,
	"enabled" boolean DEFAULT true NOT NULL,
	"auto_publish" boolean DEFAULT false NOT NULL,
	"kind_filter" "post_kind",
	"last_status" text,
	"last_error" text,
	"last_at" timestamp with time zone,
	"delivered_count" integer DEFAULT 0 NOT NULL,
	"failed_count" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "social_channels_enabled_idx" ON "social_channels" USING btree ("enabled","auto_publish");

-- The table holds encrypted bot tokens, so nothing may reach it except the
-- server's own connection. No policy is defined, which with RLS enabled means
-- no anon or authenticated role can read a row at all.
ALTER TABLE "social_channels" ENABLE ROW LEVEL SECURITY;

-- ─────────────────────────────────────────────────────────────
-- 0013_marvelous_living_mummy.sql

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$CREATE TYPE "public"."group_role" AS ENUM('owner', 'admin', 'member')$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$CREATE TYPE "public"."group_visibility" AS ENUM('public', 'private')$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

CREATE TABLE IF NOT EXISTS "group_members" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"group_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"role" "group_role" DEFAULT 'member' NOT NULL,
	"blocked" boolean DEFAULT false NOT NULL,
	"joined_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "group_members_group_user_uq" UNIQUE("group_id","user_id")
);

CREATE TABLE IF NOT EXISTS "groups" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"owner_user_id" uuid NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"slug" text NOT NULL,
	"visibility" "group_visibility" DEFAULT 'public' NOT NULL,
	"invite_code" text NOT NULL,
	"member_count" integer DEFAULT 1 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "groups_slug_unique" UNIQUE("slug"),
	CONSTRAINT "groups_invite_code_unique" UNIQUE("invite_code")
);

ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "avatar_url" text;

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$ALTER TABLE "group_members" ADD CONSTRAINT "group_members_group_id_groups_id_fk" FOREIGN KEY ("group_id") REFERENCES "public"."groups"("id") ON DELETE cascade ON UPDATE no action$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$ALTER TABLE "group_members" ADD CONSTRAINT "group_members_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

DO $lambda_guard$ BEGIN
  EXECUTE $lambda_stmt$ALTER TABLE "groups" ADD CONSTRAINT "groups_owner_user_id_users_id_fk" FOREIGN KEY ("owner_user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action$lambda_stmt$;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END $lambda_guard$;

CREATE INDEX IF NOT EXISTS "group_members_user_idx" ON "group_members" USING btree ("user_id");

CREATE INDEX IF NOT EXISTS "groups_owner_idx" ON "groups" USING btree ("owner_user_id");

-- Group membership is private to the app's own connection, like every other
-- table here: no policy is defined, so with RLS on, no anon or authenticated
-- role can read a row directly.
ALTER TABLE "groups" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "group_members" ENABLE ROW LEVEL SECURITY;

-- ─────────────────────────────────────────────────────────────
-- 0014_investigation_history.sql

-- Investigation history.
--
-- \`investigations\` already recorded the domain gateway's archive. History needs
-- two more facts to be useful: which gateway produced the run, and how much it
-- found — so a list can say "Ownership · Nestle · 12 findings · 2 days ago"
-- without loading every finding to count them.
--
-- Both are nullable: rows written before this migration are real history and
-- must not be discarded to make a column non-null.
ALTER TABLE "investigations" ADD COLUMN IF NOT EXISTS "gateway" text;

ALTER TABLE "investigations" ADD COLUMN IF NOT EXISTS "finding_count" integer DEFAULT 0 NOT NULL;

-- The history list is always "this user's, newest first", optionally filtered by
-- gateway. One composite index serves both.
CREATE INDEX IF NOT EXISTS "investigations_user_created_idx" ON "investigations" ("user_id","created_at" DESC);

CREATE INDEX IF NOT EXISTS "investigations_user_gateway_idx" ON "investigations" ("user_id","gateway");

-- ─────────────────────────────────────────────────────────────
-- 0015_usernames.sql

-- Public handles.
--
-- Every account gets a username: a Pi pioneer arrives with the one Pi assigned
-- them, and someone signing up off-Pi chooses one at sign-up. Both live in a
-- single namespace, because two namespaces would let an off-Pi account register
-- a name that reads as a Pi user's identity — the exact impersonation a handle
-- is meant to prevent.
--
-- Nullable, because accounts created before handles existed have none and
-- nothing may be invented for them. The unique constraint still holds: in
-- Postgres, NULLs do not collide, so any number of legacy rows can sit without
-- a handle while every real handle stays unique.
--
-- Values are stored already lowercased by the application (normalizeUsername),
-- which is what makes uniqueness case-insensitive: \`Lambda\` and \`lambda\` must
-- not be two people.

ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "username" text;

-- Backfill Pi accounts from the identity Pi already gave them, so a pioneer who
-- signed in before this migration keeps the handle they already had rather than
-- being asked to invent a second one.
UPDATE "users"
   SET "username" = lower("external_id")
 WHERE "username" IS NULL
   AND "auth_provider" = 'pi'
   AND lower("external_id") ~ '^[a-z0-9_]{3,30}$'
   AND NOT EXISTS (
     SELECT 1 FROM "users" AS other
      WHERE other."username" = lower("users"."external_id")
   );

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'users_username_uq'
  ) THEN
    ALTER TABLE "users" ADD CONSTRAINT "users_username_uq" UNIQUE ("username");
  END IF;
END $$;

-- ─────────────────────────────────────────────────────────────
-- 0016_blobs.sql

-- Durable object storage.
--
-- The storage port defaulted to the filesystem, which is a correct choice for a
-- self-hosted box with a disk and a silently wrong one everywhere this app
-- actually runs. On Netlify and Vercel the function filesystem is ephemeral:
-- a profile picture written during one request is gone by the next deploy —
-- often by the next cold start. The upload appeared to succeed, the database
-- kept a URL pointing at a file that no longer existed, and the user's picture
-- quietly reverted to their initials with nothing reporting an error.
--
-- Blobs therefore live in the database, which is the one component of this
-- platform that is already durable, backed up and shared across every instance.
-- For the sizes involved (avatars are capped at 2 MB) this is a better trade
-- than another vendor: no new key to leak, no new provider to be locked into,
-- and it works identically on every host.
--
-- The storage port is unchanged, so swapping this for S3 or Supabase Storage
-- later stays a provider switch rather than an application change (charter §4).

CREATE TABLE IF NOT EXISTS "blobs" (
  -- The storage key, e.g. 'avatars/<user-id>/<version>.png'. Versioned keys are
  -- why a replaced picture gets a new URL instead of being masked by a cache.
  "key" text PRIMARY KEY,
  "content_type" text,
  "bytes" bytea NOT NULL,
  -- Denormalised so a size query never has to read the payload.
  "size" integer NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- Avatar keys carry the owner's id as their first segment, so this index makes
-- "everything belonging to this user" a range scan. Account deletion needs it.
CREATE INDEX IF NOT EXISTS "blobs_key_prefix_idx" ON "blobs" ("key" text_pattern_ops);

-- ─────────────────────────────────────────────────────────────
-- 0017_source_health.sql

-- The platform's record of its own sources.
--
-- Every catalogue record carries an Admiralty rating we *declared*. This table
-- holds what each source has actually *done*, so the two can be compared: a
-- feed that has rotted goes on carrying its A forever unless something counts.
--
-- Aggregated per source per day rather than one row per run. A row per run
-- grows without bound and buys nothing — every question this data answers (is
-- it reachable, does it carry anything, when did it last work) is answerable
-- from daily counters, and a bounded table is one nobody has to prune.

CREATE TABLE IF NOT EXISTS "source_health_daily" (
  "source_key" text NOT NULL,
  "day" char(10) NOT NULL,
  "ok" integer DEFAULT 0 NOT NULL,
  "empty" integer DEFAULT 0 NOT NULL,
  "failed" integer DEFAULT 0 NOT NULL,
  "items" integer DEFAULT 0 NOT NULL,
  "last_error" text,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  -- One row per source per day is the whole storage model, so it is enforced
  -- here rather than by the code that writes it. The upsert depends on it.
  CONSTRAINT "source_health_daily_pk" UNIQUE("source_key","day")
);

CREATE INDEX IF NOT EXISTS "source_health_daily_day_idx" ON "source_health_daily" ("day");

-- ─────────────────────────────────────────────────────────────
-- 0018_verification_codes.sql

-- Email verification and password-reset codes.
--
-- Off-Pi accounts previously came into existence the moment somebody typed an
-- address into the form, which meant the address was never checked: a typo
-- created an account nobody could recover, and a stranger's address created an
-- account that stranger could not stop. This table is the proof step.
--
-- One live code per (email, purpose). Issuing a new one replaces the previous
-- one rather than adding to it — five valid codes in a mailbox are five chances
-- for a guess and one confused reader.
--
-- The code is never stored. \`code_hash\` is the same scrypt hash used for
-- passwords, which matters more here than for a password: six digits is a
-- keyspace of one million, so a plain-text column would hand every pending code
-- to anyone who reads a backup. scrypt makes an offline sweep cost days per
-- code; \`attempts\` makes an online one cost five tries.
--
-- Written by hand, and idempotent, because this migration is applied to
-- databases that are already live.

DO $$ BEGIN
  CREATE TYPE "public"."verification_purpose" AS ENUM('signup', 'reset');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS "verification_codes" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "email" text NOT NULL,
  "purpose" "verification_purpose" NOT NULL,
  "code_hash" text NOT NULL,
  "attempts" integer DEFAULT 0 NOT NULL,
  "expires_at" timestamp with time zone NOT NULL,
  "consumed_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "verification_codes_email_purpose_uq" UNIQUE("email", "purpose")
);

-- Expired rows are swept by age, not only when their owner comes back: a code
-- nobody returns for would otherwise sit in the table forever.
CREATE INDEX IF NOT EXISTS "verification_codes_expires_idx"
  ON "verification_codes" ("expires_at");

-- ─────────────────────────────────────────────────────────────
-- 0019_real_name.sql

-- A real name, and a switch that decides whether anyone else sees it.
--
-- \`full_name\` is what the person gave at sign-up. It is deliberately not
-- \`display_name\`: display_name answers "what goes next to this post", this
-- answers "who is this", and conflating them is how a real name ends up
-- published by a piece of code that only wanted a label.
--
-- \`show_real_name\` defaults to false, and the default is the point. On a
-- platform whose charter forbids profiling private individuals, a real name
-- that is visible until its owner finds the setting has already been published.

ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "full_name" text;

ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "show_real_name" boolean DEFAULT false NOT NULL;

-- ─────────────────────────────────────────────────────────────
-- 0020_preferences.sql

-- What a person has chosen, kept.
--
-- Every setting on the globe lived in component state, so switching tabs threw
-- all of it away. A user who spent a minute arranging the board to watch two
-- things lost that minute every time they looked at anything else — which
-- teaches them not to configure anything, and then the configurability may as
-- well not exist.
--
-- One JSON document rather than a row per key: there are eight settings, and a
-- row each means eight round trips, eight migrations, and eight chances for a
-- partial write to leave a layout nobody chose. The shape is validated on read
-- (\`lib/prefs/schema.ts\`), so a blob written by an older build degrades to
-- defaults instead of crashing the page.
--
-- Nullable, and it stays nullable: signed-out visitors keep their preferences
-- in the browser, and most visitors are signed out — the gateways are open
-- without an account by charter §1.

ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "preferences" jsonb;

-- ─────────────────────────────────────────────────────────────
-- 0021_email_followers.sql

-- People who asked to be sent the brief by email.
--
-- ## Double opt-in, and why it is not optional here
--
-- A row exists the moment somebody types an address, but it is \`pending\` and
-- nothing is ever sent to it except the one message asking whether they meant
-- it. Only a click on that link sets \`confirmed_at\`, and only a confirmed row
-- receives anything.
--
-- The reason is not etiquette. Without it, a form on a public intelligence
-- platform is a machine for mailing strangers: anyone could type anyone's
-- address and we would send it world-event briefs it never asked for, from a
-- domain whose reputation we depend on for the verification codes that sign
-- people in. One abused subscribe box takes the whole account system down with
-- it.
--
-- ## Two tokens, and neither is stored
--
-- \`confirm_token_hash\` proves the person reached their own inbox.
-- \`unsubscribe_token_hash\` lets them leave without signing in, which is what
-- one-click unsubscribe (RFC 8058) requires and what every mail provider now
-- scores a sender on. Both are hashed with the same scrypt used for passwords,
-- because a leaked backup of plain unsubscribe tokens is a leaked list of who
-- reads us, and the confirm token is a way to subscribe somebody who declined.
--
-- The unsubscribe token deliberately outlives confirmation: it is printed in
-- every message we ever send, so it cannot be single-use or one-time-only the
-- way the confirm token is.
--
-- Written by hand and idempotent, like every migration here, because it is
-- applied to databases that are already live.

CREATE TABLE IF NOT EXISTS "email_followers" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  -- Normalised (trimmed, lowercased). One subscription per address, ever.
  "email" text NOT NULL,
  -- The language their brief is written in, from the interface they asked in.
  "locale" text NOT NULL DEFAULT 'en',
  "confirm_token_hash" text NOT NULL,
  "unsubscribe_token_hash" text NOT NULL,
  -- Null until they click the link. Nothing is sent to a null row.
  "confirmed_at" timestamp with time zone,
  -- Set when they leave. The row is kept rather than deleted so that a later
  -- re-subscribe is a deliberate act and not a silently restored old one.
  "unsubscribed_at" timestamp with time zone,
  -- When we last sent them anything, so a run can skip what it already sent.
  "last_sent_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "email_followers_email_uq" UNIQUE("email")
);

-- A send picks up confirmed, still-subscribed rows. Both columns are null for
-- the overwhelming majority of the table's life, so the partial index is the
-- one that stays small.
CREATE INDEX IF NOT EXISTS "email_followers_sendable_idx"
  ON "email_followers" ("confirmed_at")
  WHERE "confirmed_at" IS NOT NULL AND "unsubscribed_at" IS NULL;

-- Unconfirmed rows are swept by age: an address somebody typed by mistake, or
-- typed for a stranger who sensibly ignored the message, must not sit here
-- forever waiting to be confirmed.
CREATE INDEX IF NOT EXISTS "email_followers_pending_idx"
  ON "email_followers" ("created_at")
  WHERE "confirmed_at" IS NULL;
`

/** How many migrations this schema was folded from. */
export const SCHEMA_MIGRATION_COUNT = 22
