/**
 * Write the build's own timestamp into a module the bundler can inline.
 *
 * ## The bug this replaces
 *
 * `next.config.mjs` had `NEXT_PUBLIC_BUILT_AT: new Date().toISOString()`, which
 * looks like a build stamp and is not one. `next.config.mjs` is evaluated once
 * per *process*, so `next start` — and every serverless cold start — runs that
 * `new Date()` again. The browser bundle carried the time of the build; the
 * server carried the time it happened to boot.
 *
 * Two failures from one line:
 *
 *  - **The fact was wrong.** The footer said "built at" and reported when the
 *    server last started, which is exactly the question the stamp exists to
 *    answer and exactly the wrong answer to it.
 *  - **Every page hydrated badly.** The two values differ, so the server HTML
 *    and the client's first render disagreed on a piece of text — React error
 *    #418, on every page carrying the footer. React then discards the server
 *    HTML and re-renders the whole document on the client. Nothing looks wrong
 *    afterwards, which is why it survived: it costs a full re-render on the
 *    slowest device in the audience and reports nothing.
 *
 * A generated module has neither problem. It is written once, at build time,
 * and inlined into both bundles by the compiler — so the server and the browser
 * are carrying the same characters, not two readings of the same clock.
 *
 * Committed to the repository, like `db/schema-sql.ts`, so a build that does not
 * run this script still compiles; `prebuild` refreshes it on every real build.
 *
 *   node scripts/build-stamp.mjs
 */
import { writeFileSync } from 'node:fs'
import { execFileSync } from 'node:child_process'

/** The commit, from whichever host built this, or from git when local. */
function commit() {
  const fromHost =
    process.env.COMMIT_REF ?? process.env.VERCEL_GIT_COMMIT_SHA ?? process.env.GITHUB_SHA
  if (fromHost && fromHost.trim()) return fromHost.trim()
  try {
    return execFileSync('git', ['rev-parse', 'HEAD'], { encoding: 'utf8' }).trim()
  } catch {
    return ''
  }
}

const builtAt = new Date().toISOString()
const sha = commit()

const file = `/**
 * Generated by scripts/build-stamp.mjs. Do not edit by hand.
 *
 * A constant rather than an environment variable read at runtime: the compiler
 * inlines it into the server and the browser bundle alike, so both report the
 * same build instead of two readings of a clock. See the script for the
 * hydration bug that made this necessary.
 */

/** When this build was produced, ISO-8601. */
export const BUILT_AT = ${JSON.stringify(builtAt)}

/** The commit it was produced from, or an empty string if nothing said. */
export const BUILT_FROM = ${JSON.stringify(sha)}
`

writeFileSync(new URL('../lib/build-stamp.ts', import.meta.url), file)
console.log(`build stamp: ${builtAt}${sha ? ` · ${sha.slice(0, 7)}` : ''}`)
