#!/usr/bin/env python3
"""Render the Source Licence & Usage Registry as a readable Markdown view.

The JSON (lib/engine/licensing/source-licence-registry.json) is the source of
truth; this file only presents it. Run after editing the JSON:

    python3 scripts/render-licence-registry.py

It writes docs/reconciliation/SOURCE_LICENSE_REGISTRY_2026-10-05.md.
"""
import collections
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / 'lib/engine/licensing/source-licence-registry.json'
OUT = ROOT / 'docs/reconciliation/SOURCE_LICENSE_REGISTRY_2026-10-05.md'

# Mirrors usagePolicy() in lib/engine/licensing/registry.ts.
POLICY = {
    'VERIFIED_ALLOWED': 'ALLOW',
    'VERIFIED_CONDITIONAL': 'ALLOW_WITH_CONDITIONS',
    'LEGAL_REVIEW_REQUIRED': 'ALLOW_UNDER_REVIEW',
    'UNCLEAR': 'ALLOW_UNDER_REVIEW',
    'RESTRICTED': 'WITHHOLD',
    'PROHIBITED': 'WITHHOLD',
    'EXPIRED_OR_CHANGED': 'WITHHOLD',
}
ORDER = list(POLICY)
KINDS = ['coded', 'catalogue', 'ckan-portal', 'username-site']
KIND_LABEL = {'coded': 'Coded', 'catalogue': 'Catalogue', 'ckan-portal': 'CKAN portals', 'username-site': 'Username sites'}
SECTIONS = [
    ('2. Withheld — RESTRICTED, PROHIBITED, EXPIRED_OR_CHANGED', ('RESTRICTED', 'PROHIBITED', 'EXPIRED_OR_CHANGED')),
    ('3. Under review — LEGAL_REVIEW_REQUIRED', ('LEGAL_REVIEW_REQUIRED',)),
    ('4. Verified with conditions', ('VERIFIED_CONDITIONAL',)),
    ('5. Verified', ('VERIFIED_ALLOWED',)),
    ('6. UNCLEAR (terms unreadable, silent, or absence of restriction only)', ('UNCLEAR',)),
]


def cell(text, limit=None):
    text = '—' if text in (None, '', []) else str(text)
    text = text.replace('|', '\\|').replace('\n', ' ')
    if limit and len(text) > limit:
        text = text[:limit].rstrip() + ' …'
    return text


def evidence(record):
    if not record['evidence_reference']:
        return '—'
    first = record['evidence_reference'][0]
    link = f" ([source]({first['url']}))" if first['url'] else ''
    more = len(record['evidence_reference']) - 1
    extra = f' (+{more} more quote{"s" if more > 1 else ""} in the JSON)' if more else ''
    return cell(first['quote'], 300) + link + extra


def main():
    records = json.loads(SRC.read_text())
    by_status = collections.Counter(r['license_status'] for r in records)
    by_kind = collections.Counter((r['license_status'], r['kind']) for r in records)
    kinds = collections.Counter(r['kind'] for r in records)
    lines = [
        '# Source Licence & Usage Registry — 2026-10-05 (R317, terms re-read in R318)',
        '',
        '| | |',
        '|---|---|',
        '| **Machine-readable source** | `lib/engine/licensing/source-licence-registry.json`, validated by `lib/engine/licensing/registry.ts` and enforced by `lib/conformance/s-invariants.test.ts` |',
        '| **This file** | Generated by `scripts/render-licence-registry.py`. Edit the JSON, then re-run the script. |',
        f"| **Records** | {len(records)} — " + ', '.join(f'{k}: {kinds[k]}' for k in KINDS) + ' |',
        "| **Status words** | Statuses describe what each provider's **own terms** say, quoted with URL and date. They are not a legal opinion. |",
        '| **Never** | VERIFIED from silence ("no restriction mentioned" is UNCLEAR); a portal\'s licence applied to its datasets; "free API" taken as commercial permission; an earlier licence kept without evidence |',
        '',
        '## 1. Summary',
        '',
        '| Status | Records | Usage policy | ' + ' | '.join(KIND_LABEL[k] for k in KINDS) + ' |',
        '|---|---|---|' + '---|' * len(KINDS),
    ]
    for status in ORDER:
        lines.append(f'| **{status}** | {by_status[status]} | {POLICY[status]} | ' + ' | '.join(str(by_kind[(status, k)]) for k in KINDS) + ' |')
    lines += [
        '',
        '**Usage policy:** ALLOW and ALLOW_WITH_CONDITIONS run (conditions met in the product). ALLOW_UNDER_REVIEW runs, flagged: temporary ambiguity is not a reason to delete a source before an alternative exists (owner R317). WITHHOLD is not registered or active, which the conformance test enforces.',
        '',
        '**R318:** every catalogue licence recorded before 2026-10-04 without evidence was re-read. None remains on an unevidenced earlier licence (a conformance test now fails if one appears). Where the terms could not be read — 403, 404, JavaScript-only pages — the record says so with the date and stays UNCLEAR.',
        '',
    ]
    header = '| Source | Kind | Provider | Status | Basis | Commercial | Display | Redistribution | Attribution | Key evidence (quoted) | Read | Conditions | Fallback |'
    rule = '|' + '---|' * 13
    for title, statuses in SECTIONS:
        rows = [r for r in records if r['license_status'] in statuses]
        lines += [f'## {title}', '', f'{len(rows)} records.', '', header, rule]
        for r in sorted(rows, key=lambda r: (r['kind'], r['source_id'])):
            read = r['evidence_reference'][0]['read_at'] if r['evidence_reference'] else r['checked_at']
            lines.append('| ' + ' | '.join([
                f"`{r['source_id']}`", r['kind'], cell(r['provider'], 80), r['license_status'], r['basis'],
                r['commercial_use'], r['public_display'], r['redistribution'], cell(r['attribution'], 80),
                evidence(r), read, cell(r['conditions'], 240), cell('; '.join(r['fallback_sources']), 160),
            ]) + ' |')
        lines.append('')
    OUT.write_text('\n'.join(lines))
    print(f'{OUT.relative_to(ROOT)}: {len(records)} records')


if __name__ == '__main__':
    main()
