/**
 * The credit each source's licence asks for, shown beside its findings.
 *
 * **Generated. Do not edit by hand.** Run `npx tsx scripts/build-credit-index.ts`
 * after changing a catalogue licence or a registry attribution;
 * `credits.test.ts` recomputes this and fails if it has drifted.
 *
 * 183 entries — sources that owe a credit and are not withheld.
 */

export interface SourceCredit {
  /** The words the provider asked for. */
  credit: string
  /** Short name of the standard licence, when there is one (links /terms#sources). */
  licence?: string
}

export const SOURCE_CREDITS: Readonly<Record<string, SourceCredit>> = {
  "abc_au": { credit: "ABC (Australia)" },
  "acsc_australia": { credit: "Australian Cyber Security Centre" },
  "afp_via_gdelt": { credit: "The GDELT Project" },
  "africa_cdc": { credit: "Africa CDC" },
  "africanews": { credit: "Africanews" },
  "ahram_egypt": { credit: "Al-Ahram" },
  "alarabiya": { credit: "Al Arabiya" },
  "allafrica": { credit: "AllAfrica" },
  "aps_algeria": { credit: "Algérie Presse Service" },
  "arxiv_cs": { credit: "arXiv", licence: "CC0 1.0" },
  "bangkokpost": { credit: "Bangkok Post" },
  "bgs_quakes": { credit: "British Geological Survey" },
  "bitcoin_optech": { credit: "Bitcoin Optech" },
  "blockstream_blocks": { credit: "Blockstream" },
  "boc_press": { credit: "Bank of Canada" },
  "bse_india": { credit: "BSE India" },
  "bsi_germany": { credit: "CERT-Bund / BSI" },
  "cbc_world": { credit: "CBC News" },
  "cert_eu": { credit: "CERT-EU (CC BY 4.0)", licence: "CC BY 4.0" },
  "cert_fr": { credit: "CERT-FR / ANSSI (Licence Ouverte 2.0)", licence: "Licence Ouverte 2.0" },
  "channel_news_asia": { credit: "CNA" },
  "clarin_ar": { credit: "Clarín" },
  "coindesk": { credit: "CoinDesk" },
  "coingecko": { credit: "Powered by CoinGecko" },
  "coingecko_asset": { credit: "Powered by CoinGecko" },
  "coingecko_board": { credit: "Powered by CoinGecko" },
  "coingecko_exchanges": { credit: "Powered by CoinGecko" },
  "coingecko_global": { credit: "Powered by CoinGecko" },
  "coingecko_series": { credit: "Powered by CoinGecko" },
  "coingecko_trending": { credit: "Powered by CoinGecko" },
  "copernicus_dataspace": { credit: "Copernicus Sentinel data" },
  "copernicus_news": { credit: "Copernicus Programme" },
  "cwa_taiwan": { credit: "Central Weather Administration" },
  "dawn_pakistan": { credit: "Dawn" },
  "dw_world": { credit: "Deutsche Welle" },
  "dwd_warnings": { credit: "Deutscher Wetterdienst (CC BY 4.0)", licence: "CC BY 4.0" },
  "ecb_policy_rate": { credit: "European Central Bank" },
  "ecb_press": { credit: "European Central Bank" },
  "ecb_reference_rates": { credit: "European Central Bank" },
  "ecb_yield_curve": { credit: "European Central Bank" },
  "ecdc_threats": { credit: "European Centre for Disease Prevention and Control (ECDC), CC BY 4.0", licence: "CC BY 4.0" },
  "elexon_grid": { credit: "Contains BMRS data © Elexon Limited copyright and database right" },
  "elpais_america": { credit: "El País" },
  "emsc_quakes": { credit: "EMSC — European-Mediterranean Seismological Centre (CC BY 4.0)", licence: "CC BY 4.0" },
  "entsoe_transparency": { credit: "ENTSO-E Transparency Platform" },
  "esma_eu": { credit: "European Securities and Markets Authority" },
  "ethereum_foundation_blog": { credit: "Ethereum Foundation" },
  "ethiopia_addisstandard": { credit: "Addis Standard" },
  "eu_sanctions_map": { credit: "Council of the EU" },
  "euronews": { credit: "Euronews" },
  "eurostat_hpi": { credit: "Eurostat" },
  "eurostat_releases": { credit: "Eurostat (CC BY 4.0)", licence: "CC BY 4.0" },
  "factcheck_org": { credit: "FactCheck.org" },
  "france24": { credit: "France 24" },
  "france24_arabic": { credit: "France 24" },
  "frankfurter": { credit: "European Central Bank" },
  "frankfurter_board": { credit: "European Central Bank" },
  "fred_commodities": { credit: "FRED, Federal Reserve Bank of St. Louis" },
  "fred_housing": { credit: "FRED, Federal Reserve Bank of St. Louis" },
  "fred_indices": { credit: "FRED, Federal Reserve Bank of St. Louis" },
  "fullfact": { credit: "Full Fact" },
  "ga_quakes": { credit: "© Commonwealth of Australia (Geoscience Australia) (CC BY 4.0)", licence: "CC BY 4.0" },
  "gdacs": { credit: "GDACS — European Commission JRC", licence: "CC BY 4.0" },
  "gdacs_alerts": { credit: "GDACS — European Commission JRC / UN OCHA (CC BY 4.0)", licence: "CC BY 4.0" },
  "gdelt": { credit: "The GDELT Project (gdeltproject.org)" },
  "geonet_quakes": { credit: "GeoNet / Earth Sciences New Zealand (CC BY 3.0 NZ)", licence: "CC BY 3.0 NZ" },
  "github_advisories": { credit: "GitHub Security Advisories" },
  "gov_uk_aaib": { credit: "Contains public sector information licensed under the Open Government Licence v3.0 (AAIB)", licence: "Open Government Licence v3.0" },
  "gov_uk_maib": { credit: "Contains public sector information licensed under the Open Government Licence v3.0 (MAIB)", licence: "Open Government Licence v3.0" },
  "iea_news": { credit: "IEA" },
  "ietf_rfc": { credit: "IETF Trust" },
  "ifrc_appeals": { credit: "IFRC GO" },
  "ign_spain_quakes": { credit: "© Instituto Geográfico Nacional (CC BY 4.0)", licence: "CC BY 4.0" },
  "imd_india": { credit: "India Meteorological Department" },
  "imf_commodities": { credit: "FRED, Federal Reserve Bank of St. Louis" },
  "imf_news": { credit: "International Monetary Fund" },
  "ingv_quakes": { credit: "INGV — Istituto Nazionale di Geofisica e Vulcanologia (CC BY 4.0)", licence: "CC BY 4.0" },
  "inmet_brazil": { credit: "INMET" },
  "internet_outage_isoc": { credit: "Internet Society Pulse" },
  "irena_news": { credit: "IRENA" },
  "jakartapost": { credit: "The Jakarta Post" },
  "jma_quakes": { credit: "出典：気象庁ホームページ (Japan Meteorological Agency)", licence: "CC BY 4.0" },
  "jpcert": { credit: "JPCERT/CC" },
  "kathmandupost": { credit: "The Kathmandu Post" },
  "kma_korea": { credit: "Korea Meteorological Administration" },
  "krebs": { credit: "Krebs on Security" },
  "kyivindependent": { credit: "The Kyiv Independent" },
  "lead_stories": { credit: "Lead Stories" },
  "lemonde_international": { credit: "Le Monde" },
  "map_morocco": { credit: "Maghreb Arabe Presse" },
  "mempool_blocks": { credit: "mempool.space" },
  "mempool_space": { credit: "mempool.space" },
  "meteoalarm_andorra": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_austria": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_belgium": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_bosnia_herzegovina": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_bulgaria": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_croatia": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_cyprus": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_czechia": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_denmark": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_estonia": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_finland": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_france": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_germany": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_greece": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_hungary": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_iceland": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_ireland": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_israel": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_italy": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_latvia": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_lithuania": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_luxembourg": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_malta": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_moldova": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_montenegro": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_netherlands": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_norway": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_poland": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_portugal": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_republic_of_north_macedonia": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_romania": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_serbia": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_slovakia": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_slovenia": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_spain": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_sweden": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_switzerland": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_ukraine": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "meteoalarm_united_kingdom": { credit: "MeteoAlarm / EUMETNET (CC BY 4.0)", licence: "CC BY 4.0" },
  "metoffice_warnings": { credit: "Contains public sector information licensed under the Open Government Licence v3.0 (Met Office)", licence: "Open Government Licence v3.0" },
  "nation_kenya": { credit: "Nation Media Group" },
  "ncsc_uk": { credit: "Contains public sector information licensed under the Open Government Licence v3.0 (NCSC)", licence: "Open Government Licence v3.0" },
  "ndtv_india": { credit: "NDTV" },
  "news24_za": { credit: "News24" },
  "nominatim": { credit: "© OpenStreetMap contributors", licence: "ODbL 1.0" },
  "nsidc_news": { credit: "NSIDC" },
  "oecd_newsroom": { credit: "OECD" },
  "ons_uk": { credit: "Source: Office for National Statistics licensed under the Open Government Licence v3.0", licence: "Open Government Licence v3.0" },
  "ooni_measurements": { credit: "OONI" },
  "opec_press": { credit: "OPEC" },
  "openaq_latest": { credit: "OpenAQ contributors" },
  "openaq_measurements": { credit: "OpenAQ" },
  "osv_dev": { credit: "OSV.dev and the originating advisory database", licence: "CC BY 4.0" },
  "pagasa_philippines": { credit: "PAGASA" },
  "paho_alerts": { credit: "PAHO" },
  "paho_news": { credit: "PAHO/WHO" },
  "pi_network_blog": { credit: "Pi Core Team" },
  "pm25_lass": { credit: "LASS PM2.5 open data" },
  "project_zero": { credit: "Google Project Zero" },
  "punch_nigeria": { credit: "The Punch" },
  "rba_media": { credit: "Reserve Bank of Australia (CC BY 4.0)", licence: "CC BY 4.0" },
  "rbi_india": { credit: "Reserve Bank of India" },
  "redhat_security": { credit: "Red Hat" },
  "reuters_world": { credit: "Reuters" },
  "rferl": { credit: "RFE/RL" },
  "rnz_pacific": { credit: "RNZ" },
  "saws_south_africa": { credit: "South African Weather Service" },
  "science_news": { credit: "Science / AAAS" },
  "si_volcano_weekly": { credit: "Smithsonian Global Volcanism Program" },
  "skynewsarabia": { credit: "Sky News Arabia" },
  "smn_mexico": { credit: "SMN / CONAGUA" },
  "snb_press": { credit: "Swiss National Bank" },
  "ted_europa": { credit: "Publications Office of the EU (TED)" },
  "thehackernews": { credit: "The Hacker News" },
  "ubuntu_usn": { credit: "Canonical" },
  "uk_carbon_intensity": { credit: "National Grid ESO, Carbon Intensity API" },
  "uk_companies_house": { credit: "Companies House, Open Government Licence v3.0" },
  "uk_gazette": { credit: "Contains public sector information licensed under the Open Government Licence v3.0 (The Gazette)", licence: "Open Government Licence v3.0" },
  "ukhpi_landregistry": { credit: "Contains HM Land Registry data © Crown copyright and database right", licence: "Open Government Licence v3.0" },
  "ukhsa_alerts": { credit: "Contains public sector information licensed under the Open Government Licence v3.0 (UKHSA)", licence: "Open Government Licence v3.0" },
  "un_news": { credit: "United Nations" },
  "unhcr_news": { credit: "UNHCR" },
  "w3c_news": { credit: "Copyright © World Wide Web Consortium", licence: "W3C Document License" },
  "wikipedia_current": { credit: "Wikipedia contributors (CC BY-SA 4.0)", licence: "CC BY-SA 4.0" },
  "wikipedia_itn": { credit: "Wikipedia contributors", licence: "CC BY-SA 4.0" },
  "wikipedia_trending": { credit: "Wikipedia contributors", licence: "CC BY-SA 4.0" },
  "worldbank_debarred": { credit: "World Bank" },
  "worldbank_economy": { credit: "World Bank", licence: "CC BY 4.0" },
  "worldbank_procurement": { credit: "The World Bank" },
  "worldbank_projects": { credit: "World Bank", licence: "CC BY 4.0" },
  "wto_news": { credit: "World Trade Organization" },
}

/** The credit a source's licence requires, or undefined if it asks for none. */
export function creditOf(sourceKey: string): SourceCredit | undefined {
  return SOURCE_CREDITS[sourceKey]
}
