/**
 * Which publisher is behind each source key — the catalogue's independence
 * groups, and nothing else.
 *
 * **Generated. Do not edit by hand.** Run `npx tsx scripts/build-origin-index.ts`
 * after changing any `independence` field in `lib/engine/catalog/feeds/`;
 * `origins.test.ts` recomputes this from `CATALOG` and fails if it has drifted.
 *
 * It exists so the browser can group events by publisher without importing the
 * whole catalogue. See the script's header for the measurement that forced it.
 *
 * 187 entries — every source that shares a group with another.
 * Anything absent is its own group, which is what `originOf` returns for an
 * unknown key.
 */

export const SOURCE_ORIGINS: Readonly<Record<string, string>> = {
  "abc_au": "abc-au",
  "afp_via_gdelt": "gdelt-aggregate",
  "africa_cdc": "africa-cdc",
  "africanews": "euronews",
  "ahram_egypt": "ahram",
  "aljazeera_arabic": "aljazeera",
  "allafrica": "allafrica-aggregate",
  "annahar_lebanon": "annahar",
  "ap_topnews": "ap",
  "aps_algeria": "aps-dz",
  "arxiv_cs": "arxiv",
  "bbc_arabic": "bbc",
  "bbc_world": "bbc",
  "bitcoin_magazine": "bitcoin-magazine",
  "bitcoin_optech": "bitcoin-optech",
  "blockstream_blocks": "blockstream",
  "bls_us": "bls",
  "boc_press": "bankofcanada",
  "boe_uk": "boe",
  "boj_japan": "boj",
  "bom_warnings": "bom-au",
  "bse_india": "bse-india",
  "cbc_world": "cbc",
  "census_us": "us-census",
  "cftc_press": "cftc",
  "channel_news_asia": "cna",
  "cisa_advisories": "cisa",
  "cisa_kev": "cisa",
  "clarin_ar": "clarin",
  "coingecko_trending": "coingecko",
  "copernicus_dataspace": "copernicus",
  "copernicus_news": "copernicus",
  "cwa_taiwan": "cwa-tw",
  "dawn_pakistan": "dawn",
  "dw_world": "dw",
  "dwd_warnings": "dwd",
  "ecb_press": "ecb",
  "eia_today": "eia",
  "elpais_america": "elpais",
  "eluniversal_mx": "eluniversal-mx",
  "emsc_quakes": "emsc",
  "epo_ops_patents": "epo",
  "esa_observing": "esa",
  "esma_eu": "esma",
  "ethereum_foundation_blog": "ethereum-foundation",
  "ethiopia_addisstandard": "addisstandard",
  "eu_sanctions_map": "eu-council",
  "factcheck_org": "factcheck-org",
  "fca_uk": "fca",
  "fed_press": "federalreserve",
  "fed_speeches": "federalreserve",
  "feodo_tracker": "abuse-ch",
  "finra_actions": "finra",
  "folha_br": "folha",
  "france24_arabic": "france24",
  "ga_quakes": "geoscience-au",
  "global_fishing_watch": "gfw",
  "google_factcheck_tools": "google-factcheck",
  "gov_uk_aaib": "uk-gov",
  "gov_uk_maib": "uk-gov",
  "guardian_world": "guardian",
  "iea_news": "iea",
  "ietf_rfc": "ietf",
  "ign_spain_quakes": "ign-es",
  "imd_india": "imd",
  "ingv_quakes": "ingv",
  "inmet_brazil": "inmet",
  "irena_news": "irena",
  "jma_quakes": "jma",
  "kma_korea": "kma",
  "lead_stories": "lead-stories",
  "lemonde_international": "lemonde",
  "map_morocco": "map-ma",
  "mempool_blocks": "mempool-space",
  "mempool_space": "mempool-space",
  "meteoalarm_andorra": "eumetnet-meteoalarm",
  "meteoalarm_austria": "eumetnet-meteoalarm",
  "meteoalarm_belgium": "eumetnet-meteoalarm",
  "meteoalarm_bosnia_herzegovina": "eumetnet-meteoalarm",
  "meteoalarm_bulgaria": "eumetnet-meteoalarm",
  "meteoalarm_croatia": "eumetnet-meteoalarm",
  "meteoalarm_cyprus": "eumetnet-meteoalarm",
  "meteoalarm_czechia": "eumetnet-meteoalarm",
  "meteoalarm_denmark": "eumetnet-meteoalarm",
  "meteoalarm_estonia": "eumetnet-meteoalarm",
  "meteoalarm_finland": "eumetnet-meteoalarm",
  "meteoalarm_france": "eumetnet-meteoalarm",
  "meteoalarm_germany": "eumetnet-meteoalarm",
  "meteoalarm_greece": "eumetnet-meteoalarm",
  "meteoalarm_hungary": "eumetnet-meteoalarm",
  "meteoalarm_iceland": "eumetnet-meteoalarm",
  "meteoalarm_ireland": "eumetnet-meteoalarm",
  "meteoalarm_israel": "eumetnet-meteoalarm",
  "meteoalarm_italy": "eumetnet-meteoalarm",
  "meteoalarm_latvia": "eumetnet-meteoalarm",
  "meteoalarm_lithuania": "eumetnet-meteoalarm",
  "meteoalarm_luxembourg": "eumetnet-meteoalarm",
  "meteoalarm_malta": "eumetnet-meteoalarm",
  "meteoalarm_moldova": "eumetnet-meteoalarm",
  "meteoalarm_montenegro": "eumetnet-meteoalarm",
  "meteoalarm_netherlands": "eumetnet-meteoalarm",
  "meteoalarm_norway": "eumetnet-meteoalarm",
  "meteoalarm_poland": "eumetnet-meteoalarm",
  "meteoalarm_portugal": "eumetnet-meteoalarm",
  "meteoalarm_republic_of_north_macedonia": "eumetnet-meteoalarm",
  "meteoalarm_romania": "eumetnet-meteoalarm",
  "meteoalarm_serbia": "eumetnet-meteoalarm",
  "meteoalarm_slovakia": "eumetnet-meteoalarm",
  "meteoalarm_slovenia": "eumetnet-meteoalarm",
  "meteoalarm_spain": "eumetnet-meteoalarm",
  "meteoalarm_sweden": "eumetnet-meteoalarm",
  "meteoalarm_switzerland": "eumetnet-meteoalarm",
  "meteoalarm_ukraine": "eumetnet-meteoalarm",
  "meteoalarm_united_kingdom": "eumetnet-meteoalarm",
  "meteofrance_vigilance": "meteofrance",
  "metoffice_warnings": "metoffice",
  "nasa_donki": "nasa-donki",
  "nation_kenya": "nation-africa",
  "nature_news": "nature",
  "ndtv_india": "ndtv",
  "news24_za": "news24",
  "nhc_atlantic": "noaa",
  "nhc_pacific": "noaa",
  "nhk_world": "nhk",
  "nist_cyber": "nist",
  "noaa_coops_water": "noaa",
  "noaa_swpc_alerts": "noaa",
  "noaa_swpc_kindex": "noaa-swpc",
  "npr_world": "npr",
  "nrcan_quakes": "nrcan",
  "nsidc_news": "nsidc",
  "nws_alerts": "noaa",
  "oecd_newsroom": "oecd",
  "ofac_recent": "ofac",
  "ons_uk": "ons",
  "opec_press": "opec",
  "openaq_latest": "openaq",
  "pagasa_philippines": "pagasa",
  "paho_alerts": "paho",
  "paho_news": "paho",
  "pi_network_blog": "pi-core-team",
  "punch_nigeria": "punch-ng",
  "rba_media": "rba",
  "rbi_india": "rbi",
  "reliefweb_disasters": "un-ocha",
  "reliefweb_reports": "un-ocha",
  "reuters_world": "reuters",
  "ripe_atlas_anchors": "ripe",
  "ripe_stat_announced": "ripe",
  "rnz_pacific": "rnz",
  "sam_gov_exclusions": "sam-gov",
  "saws_south_africa": "saws",
  "science_news": "science-aaas",
  "scmp_news": "scmp",
  "sec_edgar_10k": "sec",
  "sec_edgar_current": "sec",
  "sec_litigation": "sec",
  "sec_press": "sec",
  "smn_mexico": "smn-mx",
  "snb_press": "snb",
  "solana_news": "solana-foundation",
  "spiegel_international": "spiegel",
  "the_hindu": "thehindu",
  "thedailystar_bd": "dailystar-bd",
  "treasury_press": "us-treasury",
  "tsunami_gov": "noaa",
  "uk_carbon_intensity": "nationalgrid-eso",
  "uk_gazette": "uk-gazette",
  "ukhsa_alerts": "ukhsa",
  "un_news": "un-news",
  "urlhaus_recent": "abuse-ch",
  "usda_reports": "usda",
  "usgs_m2m_landsat": "usgs",
  "usgs_quakes_day_m25": "usgs",
  "usgs_quakes_hour": "usgs",
  "usgs_quakes_week_significant": "usgs",
  "usgs_volcano": "usgs",
  "usgs_water_alerts": "usgs",
  "uspto_odp_patents": "uspto",
  "w3c_news": "w3c",
  "who_afro": "who",
  "who_don": "who",
  "who_emro": "who",
  "wikipedia_current": "wikipedia",
  "worldbank_debarred": "worldbank",
  "worldbank_procurement": "worldbank",
  "wto_news": "wto",
}

/**
 * The publisher behind a source key.
 *
 * An unknown key is its own origin. That is the safe default: it constrains
 * nothing that was not already constrained, where guessing a group would
 * silently merge two voices that are not the same one.
 */
export function originOf(sourceKey: string): string {
  return SOURCE_ORIGINS[sourceKey] ?? sourceKey
}
