import type { CatalogSource } from '../types'
import { PUBLIC_DOMAIN, ccBy, publicFeed } from '../licence'

/**
 * Markets, energy and commodities.
 *
 * The rating rule that matters here: an **exchange or regulator publishing
 * about its own market** is an A, because it is the record rather than a report
 * of it. A financial news outlet is a C however respected, and a research desk
 * publishing a view on an asset it also trades is a C at best whatever its
 * quality — the interest is structural, not a comment on anyone's honesty.
 *
 * Price data itself is deliberately thin here. A quote is a fact with a
 * half-life of seconds, which is a different problem from the one this
 * catalogue solves; the markets gateway handles quotes directly. What belongs
 * here is what *changes* a market: an intervention, a suspension, a supply
 * disruption, a filing.
 */
export const MARKET_SOURCES: CatalogSource[] = [
  // ── Regulators and exchanges ─────────────────────────────────────────────
  {
    key: 'sec_litigation',
    name: 'SEC — litigation releases',
    publisher: 'US Securities and Exchange Commission',
    url: 'https://www.sec.gov/rss/litigation/litreleases.xml',
    kind: 'rss',
    discipline: 'fin',
    topics: ['corporate', 'markets', 'official'],
    coverage: ['US'],
    admiralty: 'A',
    independence: 'sec',
    licence: PUBLIC_DOMAIN,
    minIntervalSec: 3600,
    keyless: true,
    note: 'Enforcement actions — where a corporate problem becomes a matter of record.',
  },
  {
    key: 'sec_press',
    name: 'SEC — press releases',
    publisher: 'US Securities and Exchange Commission',
    url: 'https://www.sec.gov/news/pressreleases.rss',
    kind: 'rss',
    discipline: 'fin',
    topics: ['markets', 'official'],
    coverage: ['US'],
    admiralty: 'A',
    independence: 'sec',
    licence: PUBLIC_DOMAIN,
    minIntervalSec: 3600,
    keyless: true,
  },
  {
    key: 'cftc_press',
    name: 'CFTC — press releases',
    publisher: 'US Commodity Futures Trading Commission',
    url: 'https://www.cftc.gov/RSS/RSSGP/rssgp.xml',
    kind: 'rss',
    discipline: 'fin',
    topics: ['markets', 'official'],
    coverage: ['US'],
    admiralty: 'A',
    independence: 'cftc',
    licence: PUBLIC_DOMAIN,
    minIntervalSec: 3600,
    keyless: true,
  },
  {
    key: 'fca_uk',
    name: 'FCA — news and warnings',
    publisher: 'UK Financial Conduct Authority',
    url: 'https://www.fca.org.uk/news/rss.xml',
    kind: 'rss',
    discipline: 'fin',
    topics: ['markets', 'corporate', 'official'],
    coverage: ['GB'],
    admiralty: 'A',
    independence: 'fca',
    licence: ccBy('FCA, Open Government Licence v3.0', 'https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/'),
    minIntervalSec: 3600,
    keyless: true,
    note: 'Includes the warning list — unauthorised firms, named by the regulator.',
  },
  {
    key: 'esma_eu',
    name: 'ESMA — news',
    publisher: 'European Securities and Markets Authority',
    url: 'https://www.esma.europa.eu/rss.xml',
    kind: 'rss',
    discipline: 'fin',
    topics: ['markets', 'official'],
    coverage: 'global',
    admiralty: 'A',
    independence: 'esma',
    licence: publicFeed('ESMA', 'https://www.esma.europa.eu/legal-notice'),
    minIntervalSec: 7200,
    keyless: true,
  },
  {
    key: 'finra_actions',
    name: 'FINRA — disciplinary actions',
    publisher: 'Financial Industry Regulatory Authority',
    url: 'https://www.finra.org/about/news-center/rss',
    kind: 'rss',
    discipline: 'fin',
    topics: ['markets', 'corporate'],
    coverage: ['US'],
    admiralty: 'A',
    independence: 'finra',
    licence: publicFeed('FINRA', 'https://www.finra.org/about/terms-and-conditions'),
    minIntervalSec: 7200,
    keyless: true,
  },

  // ── Sanctions authorities ────────────────────────────────────────────────
  {
    key: 'ofac_recent',
    name: 'OFAC — recent sanctions actions',
    publisher: 'US Treasury Office of Foreign Assets Control',
    url: 'https://ofac.treasury.gov/system/files/126/sdn.xml',
    kind: 'rss',
    discipline: 'fin',
    topics: ['sanctions'],
    coverage: 'global',
    admiralty: 'A',
    independence: 'ofac',
    licence: PUBLIC_DOMAIN,
    minIntervalSec: 21600,
    keyless: true,
    enabled: false,
    note: 'The SDN list is large and structured, not a feed; the sanctions gateway loads it directly.',
  },
  {
    key: 'treasury_press',
    name: 'US Treasury — press releases',
    publisher: 'US Department of the Treasury',
    url: 'https://home.treasury.gov/rss/press.xml',
    kind: 'rss',
    discipline: 'fin',
    topics: ['sanctions', 'economy', 'official'],
    coverage: ['US'],
    admiralty: 'A',
    independence: 'us-treasury',
    licence: PUBLIC_DOMAIN,
    minIntervalSec: 3600,
    keyless: true,
    note: 'Where a new designation is announced before it reaches any list file.',
  },
  {
    key: 'eu_sanctions_map',
    name: 'EU — sanctions and restrictive measures',
    publisher: 'Council of the European Union',
    url: 'https://www.consilium.europa.eu/en/press/press-releases/?filter=2031&rss=true',
    kind: 'rss',
    discipline: 'fin',
    topics: ['sanctions', 'official'],
    coverage: 'global',
    admiralty: 'A',
    independence: 'eu-council',
    licence: publicFeed('Council of the EU', 'https://www.consilium.europa.eu/en/legal-notice/'),
    minIntervalSec: 7200,
    keyless: true,
  },

  // ── Energy and commodities ───────────────────────────────────────────────
  {
    key: 'iea_news',
    name: 'International Energy Agency — news',
    publisher: 'International Energy Agency',
    url: 'https://www.iea.org/rss/news',
    kind: 'rss',
    discipline: 'infra',
    topics: ['energy', 'economy'],
    coverage: 'global',
    admiralty: 'A',
    independence: 'iea',
    licence: publicFeed('IEA', 'https://www.iea.org/terms'),
    minIntervalSec: 7200,
    keyless: true,
  },
  {
    key: 'opec_press',
    name: 'OPEC — press releases',
    publisher: 'Organization of the Petroleum Exporting Countries',
    url: 'https://www.opec.org/opec_web/en/rss/press_releases.xml',
    kind: 'rss',
    discipline: 'infra',
    topics: ['energy', 'economy'],
    coverage: 'global',
    admiralty: 'A',
    independence: 'opec',
    licence: publicFeed('OPEC', 'https://www.opec.org/'),
    minIntervalSec: 7200,
    keyless: true,
    note: 'A cartel announcing its own quota is the primary document, whatever one thinks of it.',
  },
  {
    key: 'eia_today',
    name: 'EIA — Today in Energy',
    publisher: 'US Energy Information Administration',
    url: 'https://www.eia.gov/rss/todayinenergy.xml',
    kind: 'rss',
    discipline: 'infra',
    topics: ['energy', 'economy'],
    coverage: 'global',
    admiralty: 'A',
    independence: 'eia',
    licence: PUBLIC_DOMAIN,
    minIntervalSec: 7200,
    keyless: true,
  },
  {
    key: 'irena_news',
    name: 'IRENA — renewable energy news',
    publisher: 'International Renewable Energy Agency',
    url: 'https://www.irena.org/rss/news',
    kind: 'rss',
    discipline: 'infra',
    topics: ['energy'],
    coverage: 'global',
    admiralty: 'A',
    independence: 'irena',
    licence: publicFeed('IRENA', 'https://www.irena.org/'),
    minIntervalSec: 21600,
    keyless: true,
  },
  {
    key: 'usda_reports',
    name: 'USDA — agricultural reports',
    publisher: 'US Department of Agriculture',
    url: 'https://www.usda.gov/rss/latest-releases.xml',
    kind: 'rss',
    discipline: 'fin',
    topics: ['economy', 'drought'],
    coverage: 'global',
    admiralty: 'A',
    independence: 'usda',
    licence: PUBLIC_DOMAIN,
    minIntervalSec: 7200,
    keyless: true,
    note: 'Crop reports move world food prices, which is a humanitarian signal as much as a market one.',
  },

  // ── Crypto and digital assets ────────────────────────────────────────────
  {
    key: 'coingecko_trending',
    name: 'CoinGecko — trending and global market data',
    publisher: 'CoinGecko',
    url: 'https://api.coingecko.com/api/v3/search/trending',
    kind: 'json',
    path: 'coins',
    discipline: 'fin',
    topics: ['markets'],
    coverage: 'global',
    // An aggregator of exchange data, not an exchange. It reports what venues
    // did; it is not the venue.
    admiralty: 'C',
    independence: 'coingecko',
    licence: publicFeed('CoinGecko', 'https://www.coingecko.com/en/terms'),
    minIntervalSec: 900,
    keyless: true,
    map: { title: 'item.name' },
  },
  {
    key: 'mempool_space',
    name: 'mempool.space — Bitcoin network state',
    publisher: 'mempool.space',
    url: 'https://mempool.space/api/v1/fees/recommended',
    kind: 'json',
    discipline: 'fin',
    topics: ['markets', 'connectivity'],
    coverage: 'global',
    // Reading the chain itself: the network is the record.
    admiralty: 'A',
    independence: 'mempool-space',
    licence: publicFeed('mempool.space', 'https://mempool.space/'),
    minIntervalSec: 300,
    keyless: true,
    enabled: false,
    note: 'Already wired by the chain gateway; catalogued for the source dossier.',
  },
]
