import type { CatalogSource } from '../types'
import { PUBLIC_DOMAIN, ccBy, publicFeed } from '../licence'

/**
 * National agencies — the layer that turns "global coverage" from a claim into
 * a fact.
 *
 * A platform indexing international wires has coverage of what the world's
 * press finds newsworthy, which is a much smaller and much more skewed set than
 * what is happening. National meteorological services, geological surveys,
 * health ministries and statistical offices publish about their own territory
 * continuously, in their own language, whether or not anyone abroad is
 * interested — and they are the authority on it.
 *
 * Two rules run through this file:
 *
 *  - **Coverage is the country, not the world.** A national service is
 *    authoritative for its own territory and nowhere else. Marking one `global`
 *    would manufacture coverage and hide a blind spot, which is exactly what
 *    the blind-spot map exists to expose.
 *  - **Each is its own independence group by default.** Two national services
 *    reporting the same cross-border storm are genuinely two observations, and
 *    that agreement is worth something precisely because neither took it from
 *    the other.
 */
export const NATIONAL_SOURCES: CatalogSource[] = [
  // ── Seismic networks ─────────────────────────────────────────────────────
  {
    key: 'jma_quakes',
    name: '気象庁 — 地震情報 (JMA earthquakes)',
    publisher: 'Japan Meteorological Agency',
    url: 'https://www.jma.go.jp/bosai/quake/data/list.json',
    kind: 'json',
    discipline: 'geoint',
    topics: ['earthquake', 'tsunami'],
    coverage: ['JP'],
    admiralty: 'A',
    independence: 'jma',
    licence: publicFeed('Japan Meteorological Agency', 'https://www.jma.go.jp/jma/kishou/info/coment.html'),
    minIntervalSec: 300,
    keyless: true,
    map: { title: 'anm', time: 'at', magnitude: 'mag' },
    note: 'The densest seismic network in the world, on its own territory.',
  },
  {
    key: 'ingv_quakes',
    name: 'INGV — terremoti recenti',
    publisher: 'Istituto Nazionale di Geofisica e Vulcanologia',
    url: 'https://webservices.ingv.it/fdsnws/event/1/query?format=text&limit=100&orderby=time',
    kind: 'json',
    discipline: 'geoint',
    topics: ['earthquake', 'volcano'],
    coverage: ['IT'],
    admiralty: 'A',
    independence: 'ingv',
    licence: ccBy('INGV', 'https://www.ingv.it/'),
    minIntervalSec: 300,
    keyless: true,
    enabled: false,
    note: 'Text response needs its own parser; catalogued now, wired when the parser lands.',
  },
  {
    key: 'ign_spain_quakes',
    name: 'IGN España — sismología',
    publisher: 'Instituto Geográfico Nacional (Spain)',
    url: 'https://www.ign.es/ign/RssTools/sismologia.xml',
    kind: 'rss',
    discipline: 'geoint',
    topics: ['earthquake'],
    coverage: ['ES'],
    admiralty: 'A',
    independence: 'ign-es',
    licence: publicFeed('IGN España', 'https://www.ign.es/'),
    minIntervalSec: 600,
    keyless: true,
  },
  {
    key: 'ga_quakes',
    name: 'Geoscience Australia — earthquakes',
    publisher: 'Geoscience Australia',
    url: 'https://earthquakes.ga.gov.au/feeds/atom.xml',
    kind: 'atom',
    discipline: 'geoint',
    topics: ['earthquake'],
    coverage: ['AU'],
    admiralty: 'A',
    independence: 'geoscience-au',
    licence: ccBy('Geoscience Australia', 'https://www.ga.gov.au/copyright'),
    minIntervalSec: 600,
    keyless: true,
  },
  {
    key: 'nrcan_quakes',
    name: 'Natural Resources Canada — earthquakes',
    publisher: 'Natural Resources Canada',
    url: 'https://earthquakescanada.nrcan.gc.ca/index-en.php?tpl_region=canada&tpl_output=rss',
    kind: 'rss',
    discipline: 'geoint',
    topics: ['earthquake'],
    coverage: ['CA'],
    admiralty: 'A',
    independence: 'nrcan',
    licence: ccBy('Natural Resources Canada, Open Government Licence', 'https://open.canada.ca/en/open-government-licence-canada'),
    minIntervalSec: 600,
    keyless: true,
  },

  // ── Meteorological services ──────────────────────────────────────────────
  {
    key: 'metoffice_warnings',
    name: 'Met Office — UK weather warnings',
    publisher: 'UK Met Office',
    url: 'https://www.metoffice.gov.uk/public/data/PWSCache/WarningsRSS/Region/UK',
    kind: 'rss',
    discipline: 'geoint',
    topics: ['weather', 'storm', 'flood'],
    coverage: ['GB'],
    admiralty: 'A',
    independence: 'metoffice',
    licence: ccBy('UK Met Office', 'https://www.metoffice.gov.uk/policies/legal'),
    minIntervalSec: 900,
    keyless: true,
  },
  {
    key: 'dwd_warnings',
    name: 'DWD — Wetterwarnungen',
    publisher: 'Deutscher Wetterdienst',
    url: 'https://www.dwd.de/DWD/warnungen/warnapp_gemeinden/json/warnings_gemeinde.json',
    kind: 'json',
    discipline: 'geoint',
    topics: ['weather', 'storm'],
    coverage: ['DE'],
    admiralty: 'A',
    independence: 'dwd',
    licence: ccBy('Deutscher Wetterdienst', 'https://www.dwd.de/EN/service/copyright/copyright_node.html'),
    minIntervalSec: 900,
    keyless: true,
    enabled: false,
    note: 'JSONP-wrapped payload needs unwrapping before parsing.',
  },
  {
    key: 'meteofrance_vigilance',
    name: 'Météo-France — vigilance',
    publisher: 'Météo-France',
    url: 'https://donneespubliques.meteofrance.fr/donnees_libres/Vigilance/Carte/vigilance.xml',
    kind: 'rss',
    discipline: 'geoint',
    topics: ['weather', 'storm', 'flood'],
    coverage: ['FR'],
    admiralty: 'A',
    independence: 'meteofrance',
    licence: publicFeed('Météo-France', 'https://donneespubliques.meteofrance.fr/'),
    minIntervalSec: 900,
    keyless: true,
  },
  {
    key: 'bom_warnings',
    name: 'Bureau of Meteorology — Australian warnings',
    publisher: 'Australian Bureau of Meteorology',
    url: 'https://www.bom.gov.au/fwo/IDZ00054.warnings_land_all.xml',
    kind: 'rss',
    discipline: 'geoint',
    topics: ['weather', 'storm', 'flood'],
    coverage: ['AU'],
    admiralty: 'A',
    independence: 'bom-au',
    licence: ccBy('Australian Bureau of Meteorology', 'http://www.bom.gov.au/other/copyright.shtml'),
    minIntervalSec: 900,
    keyless: true,
    enabled: false,
    note: 'The https endpoint is unverified, so this stays disabled rather than shipping a source that may 404.',
  },
  {
    key: 'imd_india',
    name: 'India Meteorological Department — warnings',
    publisher: 'India Meteorological Department',
    url: 'https://mausam.imd.gov.in/api/warnings_district_api.php',
    kind: 'json',
    discipline: 'geoint',
    topics: ['weather', 'storm', 'flood'],
    coverage: ['IN'],
    admiralty: 'A',
    independence: 'imd',
    licence: publicFeed('India Meteorological Department', 'https://mausam.imd.gov.in/'),
    minIntervalSec: 1800,
    keyless: true,
    enabled: false,
    note: 'Endpoint shape to confirm before enabling.',
  },
  {
    key: 'cwa_taiwan',
    name: '中央氣象署 — 天氣警特報',
    publisher: 'Central Weather Administration (Taiwan)',
    url: 'https://www.cwa.gov.tw/rss/Data/cwa_warning.xml',
    kind: 'rss',
    discipline: 'geoint',
    topics: ['weather', 'storm', 'earthquake'],
    coverage: ['TW'],
    admiralty: 'A',
    independence: 'cwa-tw',
    licence: publicFeed('Central Weather Administration', 'https://www.cwa.gov.tw/'),
    minIntervalSec: 900,
    keyless: true,
  },
  {
    key: 'kma_korea',
    name: '기상청 — 특보',
    publisher: 'Korea Meteorological Administration',
    url: 'https://www.weather.go.kr/w/rss/wrn.do',
    kind: 'rss',
    discipline: 'geoint',
    topics: ['weather', 'storm'],
    coverage: ['KR'],
    admiralty: 'A',
    independence: 'kma',
    licence: publicFeed('Korea Meteorological Administration', 'https://www.weather.go.kr/'),
    minIntervalSec: 900,
    keyless: true,
  },
  {
    key: 'pagasa_philippines',
    name: 'PAGASA — weather bulletins',
    publisher: 'PAGASA (Philippines)',
    url: 'https://www.pagasa.dost.gov.ph/feeds/weather-bulletin',
    kind: 'rss',
    discipline: 'geoint',
    topics: ['weather', 'storm'],
    coverage: ['PH'],
    admiralty: 'A',
    independence: 'pagasa',
    licence: publicFeed('PAGASA', 'https://www.pagasa.dost.gov.ph/'),
    minIntervalSec: 1800,
    keyless: true,
  },
  {
    key: 'inmet_brazil',
    name: 'INMET — avisos meteorológicos',
    publisher: 'Instituto Nacional de Meteorologia (Brazil)',
    url: 'https://apiprevmet3.inmet.gov.br/avisos/rss',
    kind: 'rss',
    discipline: 'geoint',
    topics: ['weather', 'storm', 'drought'],
    coverage: ['BR'],
    admiralty: 'A',
    independence: 'inmet',
    licence: publicFeed('INMET', 'https://portal.inmet.gov.br/'),
    minIntervalSec: 1800,
    keyless: true,
  },
  {
    key: 'smn_mexico',
    name: 'SMN México — avisos',
    publisher: 'Servicio Meteorológico Nacional (Mexico)',
    url: 'https://smn.conagua.gob.mx/es/rss-avisos',
    kind: 'rss',
    discipline: 'geoint',
    topics: ['weather', 'storm'],
    coverage: ['MX'],
    admiralty: 'A',
    independence: 'smn-mx',
    licence: publicFeed('SMN / CONAGUA', 'https://smn.conagua.gob.mx/'),
    minIntervalSec: 1800,
    keyless: true,
  },
  {
    key: 'saws_south_africa',
    name: 'South African Weather Service — warnings',
    publisher: 'South African Weather Service',
    url: 'https://www.weathersa.co.za/home/rssfeed',
    kind: 'rss',
    discipline: 'geoint',
    topics: ['weather', 'storm', 'drought'],
    coverage: ['ZA'],
    admiralty: 'A',
    independence: 'saws',
    licence: publicFeed('South African Weather Service', 'https://www.weathersa.co.za/'),
    minIntervalSec: 1800,
    keyless: true,
  },

  // ── Health authorities ───────────────────────────────────────────────────
  {
    key: 'ukhsa_alerts',
    name: 'UKHSA — health protection reports',
    publisher: 'UK Health Security Agency',
    url: 'https://www.gov.uk/government/organisations/uk-health-security-agency.atom',
    kind: 'atom',
    discipline: 'humint',
    topics: ['health'],
    coverage: ['GB'],
    admiralty: 'A',
    independence: 'ukhsa',
    licence: ccBy('UKHSA, Open Government Licence v3.0', 'https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/'),
    minIntervalSec: 3600,
    keyless: true,
  },
  {
    key: 'paho_alerts',
    name: 'PAHO — epidemiological alerts',
    publisher: 'Pan American Health Organization',
    url: 'https://www.paho.org/en/rss/epidemiological-alerts-and-updates',
    kind: 'rss',
    discipline: 'humint',
    topics: ['health'],
    coverage: 'global',
    admiralty: 'A',
    independence: 'paho',
    licence: ccBy('PAHO', 'https://www.paho.org/en/copyright'),
    minIntervalSec: 7200,
    keyless: true,
  },
  {
    key: 'africa_cdc',
    name: 'Africa CDC — outbreak briefs',
    publisher: 'Africa Centres for Disease Control and Prevention',
    url: 'https://africacdc.org/feed/',
    kind: 'rss',
    discipline: 'humint',
    topics: ['health'],
    coverage: 'global',
    admiralty: 'A',
    independence: 'africa-cdc',
    licence: publicFeed('Africa CDC', 'https://africacdc.org/'),
    minIntervalSec: 7200,
    keyless: true,
    note: 'Continental coverage that no international wire provides consistently.',
  },
  {
    key: 'who_afro',
    name: 'WHO Africa — outbreaks and emergencies',
    publisher: 'World Health Organization — Regional Office for Africa',
    url: 'https://www.afro.who.int/rss/news.xml',
    kind: 'rss',
    discipline: 'humint',
    topics: ['health'],
    coverage: 'global',
    admiralty: 'A',
    // Same organisation as `who_don`, so the same group: a regional office
    // repeating headquarters is not a second confirmation.
    independence: 'who',
    licence: publicFeed('WHO Africa', 'https://www.who.int/about/policies/terms-of-use'),
    minIntervalSec: 7200,
    keyless: true,
  },
  {
    key: 'who_emro',
    name: 'WHO Eastern Mediterranean — news',
    publisher: 'World Health Organization — EMRO',
    url: 'https://www.emro.who.int/rss.xml',
    kind: 'rss',
    discipline: 'humint',
    topics: ['health'],
    coverage: 'global',
    admiralty: 'A',
    independence: 'who',
    licence: publicFeed('WHO EMRO', 'https://www.who.int/about/policies/terms-of-use'),
    minIntervalSec: 7200,
    keyless: true,
    enabled: false,
    note: 'The https endpoint is unverified, so this stays disabled rather than shipping a source that may 404.',
  },

  // ── Statistical and economic offices ─────────────────────────────────────
  {
    key: 'ons_uk',
    name: 'ONS — UK statistical releases',
    publisher: 'Office for National Statistics (UK)',
    url: 'https://www.ons.gov.uk/releasecalendar?rss',
    kind: 'rss',
    discipline: 'fin',
    topics: ['economy'],
    coverage: ['GB'],
    admiralty: 'A',
    independence: 'ons',
    licence: ccBy('ONS, Open Government Licence v3.0', 'https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/'),
    minIntervalSec: 7200,
    keyless: true,
  },
  {
    key: 'bls_us',
    name: 'US Bureau of Labor Statistics — releases',
    publisher: 'US Bureau of Labor Statistics',
    url: 'https://www.bls.gov/feed/bls_latest.rss',
    kind: 'rss',
    discipline: 'fin',
    topics: ['economy'],
    coverage: ['US'],
    admiralty: 'A',
    independence: 'bls',
    licence: PUBLIC_DOMAIN,
    minIntervalSec: 7200,
    keyless: true,
  },
  {
    key: 'census_us',
    name: 'US Census Bureau — economic indicators',
    publisher: 'US Census Bureau',
    url: 'https://www.census.gov/economic-indicators/indicator.xml',
    kind: 'rss',
    discipline: 'fin',
    topics: ['economy'],
    coverage: ['US'],
    admiralty: 'A',
    independence: 'us-census',
    licence: PUBLIC_DOMAIN,
    minIntervalSec: 7200,
    keyless: true,
  },
  {
    key: 'boj_japan',
    name: 'Bank of Japan — releases',
    publisher: 'Bank of Japan',
    url: 'https://www.boj.or.jp/en/rss/whatsnew.xml',
    kind: 'rss',
    discipline: 'fin',
    topics: ['economy', 'markets', 'official'],
    coverage: ['JP'],
    admiralty: 'A',
    independence: 'boj',
    licence: publicFeed('Bank of Japan', 'https://www.boj.or.jp/en/'),
    minIntervalSec: 7200,
    keyless: true,
  },
  {
    key: 'boe_uk',
    name: 'Bank of England — news and publications',
    publisher: 'Bank of England',
    url: 'https://www.bankofengland.co.uk/rss/news',
    kind: 'rss',
    discipline: 'fin',
    topics: ['economy', 'markets', 'official'],
    coverage: ['GB'],
    admiralty: 'A',
    independence: 'boe',
    licence: publicFeed('Bank of England', 'https://www.bankofengland.co.uk/legal'),
    minIntervalSec: 7200,
    keyless: true,
  },
  {
    key: 'rbi_india',
    name: 'Reserve Bank of India — press releases',
    publisher: 'Reserve Bank of India',
    url: 'https://www.rbi.org.in/pressreleases_rss.xml',
    kind: 'rss',
    discipline: 'fin',
    topics: ['economy', 'official'],
    coverage: ['IN'],
    admiralty: 'A',
    independence: 'rbi',
    licence: publicFeed('Reserve Bank of India', 'https://www.rbi.org.in/'),
    minIntervalSec: 7200,
    keyless: true,
  },
  {
    key: 'oecd_newsroom',
    name: 'OECD — newsroom',
    publisher: 'Organisation for Economic Co-operation and Development',
    url: 'https://www.oecd.org/newsroom/index.xml',
    kind: 'rss',
    discipline: 'fin',
    topics: ['economy', 'official'],
    coverage: 'global',
    admiralty: 'A',
    independence: 'oecd',
    licence: publicFeed('OECD', 'https://www.oecd.org/termsandconditions/'),
    minIntervalSec: 7200,
    keyless: true,
  },
  {
    key: 'wto_news',
    name: 'WTO — news',
    publisher: 'World Trade Organization',
    url: 'https://www.wto.org/library/rss/latest_news_e.xml',
    kind: 'rss',
    discipline: 'fin',
    topics: ['economy', 'official'],
    coverage: 'global',
    admiralty: 'A',
    independence: 'wto',
    licence: publicFeed('World Trade Organization', 'https://www.wto.org/english/info_e/cpyrit_e.htm'),
    minIntervalSec: 7200,
    keyless: true,
  },
]
