import type { CatalogSource } from '../types'
import { publicFeed } from '../licence'

/**
 * The long tail of regional reporting.
 *
 * `regional.ts` covers the large multilingual broadcasters. This file covers
 * what they miss: national and regional outlets whose entire readership is one
 * country, publishing in the language spoken there.
 *
 * That is where the coverage actually comes from. An international broadcaster
 * has a bureau in a capital; a national outlet has correspondents in provinces
 * the bureau will never visit. For most of the world, the second is the only
 * reporting that exists, and a platform without it is claiming global coverage
 * on the strength of a few dozen foreign desks.
 *
 * **A word on ratings.** Several of these are state-owned or state-adjacent.
 * That is recorded in the rating, not hidden and not editorialised: a
 * state-controlled outlet reporting on its own government is not an independent
 * observer of it, whatever its production values. Those are rated C or D, the
 * reason is written beside them, and the corroboration engine treats them as
 * exactly one origin like everyone else. The judgement is coarse, visible, and
 * arguable — which is the most that can honestly be claimed for it.
 */
export const REGIONAL_EXTRA_SOURCES: CatalogSource[] = [
  // ── Arabic-language ──────────────────────────────────────────────────────
  {
    key: 'alarabiya',
    name: 'العربية',
    publisher: 'Al Arabiya Network',
    url: 'https://www.alarabiya.net/tools/rss/ar.xml',
    kind: 'rss',
    discipline: 'osint',
    topics: ['news'],
    coverage: 'global',
    admiralty: 'C',
    independence: 'alarabiya',
    licence: publicFeed('Al Arabiya', 'https://www.alarabiya.net/'),
    minIntervalSec: 1800,
    keyless: true,
  },
  {
    key: 'skynewsarabia',
    name: 'سكاي نيوز عربية',
    publisher: 'Sky News Arabia',
    url: 'https://www.skynewsarabia.com/web/rss/95.xml',
    kind: 'rss',
    discipline: 'osint',
    topics: ['news'],
    coverage: 'global',
    admiralty: 'C',
    independence: 'skynewsarabia',
    licence: publicFeed('Sky News Arabia', 'https://www.skynewsarabia.com/'),
    minIntervalSec: 1800,
    keyless: true,
  },
  {
    key: 'aps_algeria',
    name: 'وكالة الأنباء الجزائرية (APS)',
    publisher: 'Algérie Presse Service',
    url: 'https://www.aps.dz/ar/rss',
    kind: 'rss',
    discipline: 'osint',
    topics: ['news', 'official'],
    coverage: ['DZ'],
    // A state news agency: the primary record of what the state says, and not
    // an independent observer of it. Both halves matter.
    admiralty: 'C',
    independence: 'aps-dz',
    licence: publicFeed('Algérie Presse Service', 'https://www.aps.dz/'),
    minIntervalSec: 1800,
    keyless: true,
    note: 'State agency: authoritative for official positions, not for scrutiny of them.',
  },
  {
    key: 'map_morocco',
    name: 'وكالة المغرب العربي للأنباء',
    publisher: 'Maghreb Arabe Presse',
    url: 'https://www.mapnews.ma/ar/rss.xml',
    kind: 'rss',
    discipline: 'osint',
    topics: ['news', 'official'],
    coverage: ['MA'],
    admiralty: 'C',
    independence: 'map-ma',
    licence: publicFeed('Maghreb Arabe Presse', 'https://www.mapnews.ma/'),
    minIntervalSec: 1800,
    keyless: true,
    note: 'State agency — see the note on APS.',
  },
  {
    key: 'ahram_egypt',
    name: 'الأهرام',
    publisher: 'Al-Ahram',
    url: 'https://gate.ahram.org.eg/RSS/1.aspx',
    kind: 'rss',
    discipline: 'osint',
    topics: ['news'],
    coverage: ['EG'],
    admiralty: 'C',
    independence: 'ahram',
    licence: publicFeed('Al-Ahram', 'https://gate.ahram.org.eg/'),
    minIntervalSec: 1800,
    keyless: true,
  },
  {
    key: 'annahar_lebanon',
    name: 'النهار',
    publisher: 'An-Nahar',
    url: 'https://www.annahar.com/rss/latest-news.xml',
    kind: 'rss',
    discipline: 'osint',
    topics: ['news'],
    coverage: ['LB'],
    admiralty: 'C',
    independence: 'annahar',
    licence: publicFeed('An-Nahar', 'https://www.annahar.com/'),
    minIntervalSec: 1800,
    keyless: true,
  },

  // ── South Asia ───────────────────────────────────────────────────────────
  {
    key: 'ndtv_india',
    name: 'NDTV — top stories',
    publisher: 'NDTV',
    url: 'https://feeds.feedburner.com/ndtvnews-top-stories',
    kind: 'rss',
    discipline: 'osint',
    topics: ['news'],
    coverage: ['IN'],
    admiralty: 'C',
    independence: 'ndtv',
    licence: publicFeed('NDTV', 'https://www.ndtv.com/'),
    minIntervalSec: 1800,
    keyless: true,
  },
  {
    key: 'dawn_pakistan',
    name: 'Dawn',
    publisher: 'Dawn Media Group',
    url: 'https://www.dawn.com/feeds/home',
    kind: 'rss',
    discipline: 'osint',
    topics: ['news'],
    coverage: ['PK'],
    admiralty: 'B',
    independence: 'dawn',
    licence: publicFeed('Dawn', 'https://www.dawn.com/terms'),
    minIntervalSec: 1800,
    keyless: true,
  },
  {
    key: 'thedailystar_bd',
    name: 'The Daily Star',
    publisher: 'The Daily Star (Bangladesh)',
    url: 'https://www.thedailystar.net/frontpage/rss.xml',
    kind: 'rss',
    discipline: 'osint',
    topics: ['news'],
    coverage: ['BD'],
    admiralty: 'B',
    independence: 'dailystar-bd',
    licence: publicFeed('The Daily Star', 'https://www.thedailystar.net/'),
    minIntervalSec: 1800,
    keyless: true,
  },
  {
    key: 'kathmandupost',
    name: 'The Kathmandu Post',
    publisher: 'Kantipur Media Group',
    url: 'https://kathmandupost.com/rss',
    kind: 'rss',
    discipline: 'osint',
    topics: ['news'],
    coverage: ['NP'],
    admiralty: 'B',
    independence: 'kathmandupost',
    licence: publicFeed('The Kathmandu Post', 'https://kathmandupost.com/'),
    minIntervalSec: 3600,
    keyless: true,
    note: 'Himalayan seismic and flood reporting no wire covers routinely.',
  },

  // ── Africa ───────────────────────────────────────────────────────────────
  {
    key: 'nation_kenya',
    name: 'Daily Nation',
    publisher: 'Nation Media Group',
    url: 'https://nation.africa/kenya/rss',
    kind: 'rss',
    discipline: 'osint',
    topics: ['news'],
    coverage: ['KE'],
    admiralty: 'B',
    independence: 'nation-africa',
    licence: publicFeed('Nation Media Group', 'https://nation.africa/'),
    minIntervalSec: 1800,
    keyless: true,
  },
  {
    key: 'punch_nigeria',
    name: 'The Punch',
    publisher: 'Punch Nigeria',
    url: 'https://punchng.com/feed/',
    kind: 'rss',
    discipline: 'osint',
    topics: ['news'],
    coverage: ['NG'],
    admiralty: 'C',
    independence: 'punch-ng',
    licence: publicFeed('The Punch', 'https://punchng.com/'),
    minIntervalSec: 1800,
    keyless: true,
  },
  {
    key: 'news24_za',
    name: 'News24',
    publisher: 'Media24',
    url: 'https://feeds.24.com/articles/news24/TopStories/rss',
    kind: 'rss',
    discipline: 'osint',
    topics: ['news'],
    coverage: ['ZA'],
    admiralty: 'B',
    independence: 'news24',
    licence: publicFeed('News24', 'https://www.news24.com/'),
    minIntervalSec: 1800,
    keyless: true,
  },
  {
    key: 'ethiopia_addisstandard',
    name: 'Addis Standard',
    publisher: 'Addis Standard',
    url: 'https://addisstandard.com/feed/',
    kind: 'rss',
    discipline: 'osint',
    topics: ['news', 'conflict'],
    coverage: ['ET'],
    admiralty: 'C',
    independence: 'addisstandard',
    licence: publicFeed('Addis Standard', 'https://addisstandard.com/'),
    minIntervalSec: 3600,
    keyless: true,
    note: 'Horn of Africa coverage that international wires reach late or not at all.',
  },

  // ── Latin America ────────────────────────────────────────────────────────
  {
    key: 'clarin_ar',
    name: 'Clarín',
    publisher: 'Grupo Clarín',
    url: 'https://www.clarin.com/rss/lo-ultimo/',
    kind: 'rss',
    discipline: 'osint',
    topics: ['news'],
    coverage: ['AR'],
    admiralty: 'C',
    independence: 'clarin',
    licence: publicFeed('Clarín', 'https://www.clarin.com/'),
    minIntervalSec: 1800,
    keyless: true,
  },
  {
    key: 'folha_br',
    name: 'Folha de S.Paulo',
    publisher: 'Grupo Folha',
    url: 'https://feeds.folha.uol.com.br/emcimadahora/rss091.xml',
    kind: 'rss',
    discipline: 'osint',
    topics: ['news'],
    coverage: ['BR'],
    admiralty: 'B',
    independence: 'folha',
    licence: publicFeed('Folha de S.Paulo', 'https://www.folha.uol.com.br/'),
    minIntervalSec: 1800,
    keyless: true,
  },
  {
    key: 'eluniversal_mx',
    name: 'El Universal',
    publisher: 'El Universal (Mexico)',
    url: 'https://www.eluniversal.com.mx/rss.xml',
    kind: 'rss',
    discipline: 'osint',
    topics: ['news'],
    coverage: ['MX'],
    admiralty: 'C',
    independence: 'eluniversal-mx',
    licence: publicFeed('El Universal', 'https://www.eluniversal.com.mx/'),
    minIntervalSec: 1800,
    keyless: true,
  },

  // ── Eastern Europe & Central Asia ────────────────────────────────────────
  {
    key: 'rferl',
    name: 'Radio Free Europe / Radio Liberty',
    publisher: 'RFE/RL',
    url: 'https://www.rferl.org/api/zrqiteuuir',
    kind: 'rss',
    discipline: 'osint',
    topics: ['news', 'conflict'],
    coverage: 'global',
    // US-government-funded, with editorial independence in its charter. Rated C
    // for the funding relationship, which is a structural fact rather than a
    // judgement about its journalism.
    admiralty: 'C',
    independence: 'rferl',
    licence: publicFeed('RFE/RL', 'https://www.rferl.org/p/6650.html'),
    minIntervalSec: 1800,
    keyless: true,
    note: 'Reaches Central Asian and Caucasus reporting almost nothing else covers.',
  },
  {
    key: 'kyivindependent',
    name: 'The Kyiv Independent',
    publisher: 'The Kyiv Independent',
    url: 'https://kyivindependent.com/feed/',
    kind: 'rss',
    discipline: 'osint',
    topics: ['news', 'conflict'],
    coverage: ['UA'],
    admiralty: 'C',
    independence: 'kyivindependent',
    licence: publicFeed('The Kyiv Independent', 'https://kyivindependent.com/'),
    minIntervalSec: 1800,
    keyless: true,
  },

  // ── Southeast Asia & Pacific ─────────────────────────────────────────────
  {
    key: 'jakartapost',
    name: 'The Jakarta Post',
    publisher: 'The Jakarta Post',
    url: 'https://www.thejakartapost.com/feed',
    kind: 'rss',
    discipline: 'osint',
    topics: ['news'],
    coverage: ['ID'],
    admiralty: 'B',
    independence: 'jakartapost',
    licence: publicFeed('The Jakarta Post', 'https://www.thejakartapost.com/'),
    minIntervalSec: 1800,
    keyless: true,
    note: 'The most seismically active country on earth, reported locally.',
  },
  {
    key: 'bangkokpost',
    name: 'Bangkok Post',
    publisher: 'Bangkok Post',
    url: 'https://www.bangkokpost.com/rss/data/topstories.xml',
    kind: 'rss',
    discipline: 'osint',
    topics: ['news'],
    coverage: ['TH'],
    admiralty: 'B',
    independence: 'bangkokpost',
    licence: publicFeed('Bangkok Post', 'https://www.bangkokpost.com/'),
    minIntervalSec: 1800,
    keyless: true,
  },
  {
    key: 'rnz_pacific',
    name: 'RNZ Pacific',
    publisher: 'Radio New Zealand',
    url: 'https://www.rnz.co.nz/rss/pacific.xml',
    kind: 'rss',
    discipline: 'osint',
    topics: ['news'],
    coverage: 'global',
    admiralty: 'B',
    independence: 'rnz',
    licence: publicFeed('RNZ', 'https://www.rnz.co.nz/about/terms-and-conditions'),
    minIntervalSec: 3600,
    keyless: true,
    note: 'Pacific island coverage that is otherwise a near-total blind spot.',
  },
]
